// Four real Electron clients exercise production tokens/session against LiveKit.
// Set LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET; no credentials are saved in the repo.
const { app, BrowserWindow } = require('electron')
const { build } = require('esbuild')
const { RoomServiceClient } = require('livekit-server-sdk')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const assert = require('node:assert/strict')
const root = path.resolve(__dirname, '..')
const windows = []
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
let client
const temp = require('node:fs').mkdtempSync(path.join(os.tmpdir(), 'zodiak-chat-live-'))
app.setPath('userData', path.join(temp, 'profile'))
app.setPath('sessionData', path.join(temp, 'session'))
let finishing = false
const roomName = 'codex-chat-test-' + Date.now()
const otherRoom = roomName + '-other'
const timeout = setTimeout(() => { console.error('Live chat test timed out'); void finish(1) }, 90000)
async function finish(code) {
  if (finishing) return
  finishing = true
  clearTimeout(timeout)
  if (temp) await fs.rm(path.join(temp,'profile','config.json'), {force:true})
  await Promise.race([Promise.allSettled(windows.filter(win => !win.isDestroyed()).map(win => win.webContents.executeJavaScript('window.chatTest.leave()'))),pause(5000)])
  windows.forEach(win => { if (!win.isDestroyed()) win.destroy() })
  if (client) await Promise.allSettled([client.deleteRoom(roomName), client.deleteRoom(otherRoom)])
  // Only the unique test directory generated by mkdtemp can be removed.
  if (temp && path.resolve(temp).startsWith(path.resolve(os.tmpdir()) + path.sep) && path.basename(temp).startsWith('zodiak-chat-live-')) await fs.rm(temp, { recursive: true, force: true, maxRetries:3, retryDelay:200 }).catch(() => undefined)
  app.exit(code)
}
const harness = `
import { joinRoom, leaveRoom, sendChatMessage, updateDisplayName } from './session'
import { setLogLevel, LogLevel } from 'livekit-client'
setLogLevel(LogLevel.error)
const messages = []; const errors = []; let participants = []; let connection = 'offline'; let roomLosses = 0
window.chatTest = {
  async join(url, token) {
    await joinRoom({url, token, subscribe:false, media:{video:document.createElement('video'),audioRack:document.body}, hooks:{
      onChatMessage(message){messages.push(message)}, onConnection(value){connection=value}, onParticipants(value){participants=value}, onRoomLost(){roomLosses++},
      onViewers(){},onStreams(){},onTelemetry(){},onAudioBlocked(){},onError(message){errors.push(message)}
    }})
  }, send:sendChatMessage, rename:updateDisplayName, leave:leaveRoom,
  snapshot(){return {messages,participants,connection,roomLosses,errors}}
}
`
app.whenReady().then(async () => {
  const { LIVEKIT_URL: url, LIVEKIT_API_KEY: apiKey, LIVEKIT_API_SECRET: apiSecret } = process.env
  assert(url && apiKey && apiSecret, 'Provide the three LIVEKIT_* environment variables')
  await fs.mkdir(app.getPath('userData'), { recursive: true })
  await fs.writeFile(path.join(app.getPath('userData'), 'config.json'), JSON.stringify({ url, apiKey, apiSecret, displayName:'Chat test' }))
  // Compile the actual token issuer and parser, not a duplicate grant in the test.
  await build({ entryPoints:[path.join(root, 'src/main/tokens.ts')], bundle:true, platform:'node', format:'cjs', external:['electron'], outfile:path.join(temp,'tokens.cjs') })
  const { createParticipantToken } = require(path.join(temp, 'tokens.cjs'))
  client = new RoomServiceClient(url.replace(/^ws/, 'http'), apiKey, apiSecret, { requestTimeout: 8 })
  await client.createRoom({ name: roomName }); await client.createRoom({ name: otherRoom })
  await build({ stdin:{contents:harness, resolveDir:path.join(root,'src/renderer/src'), sourcefile:'chat-live-harness.ts'}, bundle:true, format:'iife', outfile:path.join(temp,'harness.js') })
  await fs.writeFile(path.join(temp,'index.html'), '<!doctype html><script src="./harness.js"></script>')
  const tokens = []
  for (const [index, name] of ['Alice','Bob','Carol','Dave'].entries()) {
    const issued = await createParticipantToken({ role:'viewer', displayName:name, room:index===3 ? otherRoom : roomName })
    const claims = JSON.parse(Buffer.from(issued.token.split('.')[1], 'base64url').toString())
    assert.equal(claims.video.canPublishData, true)
    assert.deepEqual(claims.video.canPublishSources, ['screen_share','screen_share_audio','microphone'])
    const win = new BrowserWindow({ show:false, webPreferences:{contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:true} })
    windows.push(win); tokens.push(issued)
    await win.loadFile(path.join(temp,'index.html'))
    await win.webContents.executeJavaScript(`window.chatTest.join(${JSON.stringify(issued.url)},${JSON.stringify(issued.token)})`)
  }
  const run = (index, code) => windows[index].webContents.executeJavaScript(code)
  const snapshot = index => run(index,'window.chatTest.snapshot()')
  for (let attempt=0; attempt<30; attempt++) {
    if ((await snapshot(0)).participants.length===3 && (await snapshot(2)).participants.length===3) break
    await pause(200)
  }
  assert.equal((await snapshot(0)).participants.length,3)
  console.log('PASS Four clients connect using production room-scoped data grants')
  await run(0,`window.chatTest.send('Room broadcast')`); await pause(500)
  assert.equal((await snapshot(1)).messages[0].text,'Room broadcast')
  assert.equal((await snapshot(2)).messages[0].text,'Room broadcast')
  assert.equal((await snapshot(3)).messages.length,0)
  console.log('PASS Public message reaches the same room, never another room')
  const privateMessage = await run(0,`window.chatTest.send('Only Bob',${JSON.stringify(tokens[1].identity)})`); await pause(500)
  assert.equal(privateMessage.recipient,tokens[1].identity)
  assert.equal((await snapshot(1)).messages.at(-1).text,'Only Bob')
  assert.equal((await snapshot(2)).messages.length,1)
  assert.equal((await snapshot(3)).messages.length,0)
  console.log('PASS Whisper reaches only its recipient, not a third room participant')
  await run(1,`window.chatTest.send('Only Alice',${JSON.stringify(tokens[0].identity)})`); await pause(500)
  assert.equal((await snapshot(0)).messages.at(-1).text,'Only Alice')
  assert.equal((await snapshot(2)).messages.length,1)
  console.log('PASS Private reply routes back to the authenticated sender')
  await run(0,`window.chatTest.rename('Renamed Alice')`); await pause(300)
  await run(0,`window.chatTest.send('Updated identity')`); await pause(400)
  assert.equal((await snapshot(1)).messages.at(-1).senderName,'Renamed Alice')
  console.log('PASS Sender name comes from LiveKit and follows profile changes')
  await run(0,`window.chatTest.send('😀'.repeat(1000))`); await pause(400)
  assert.equal((await snapshot(1)).messages.at(-1).text.length,2000)
  await assert.rejects(run(0,`window.chatTest.send('x'.repeat(2001))`), /2000/)
  console.log('PASS Unicode messages fit the packet budget and oversize messages are rejected')
  await run(1,'window.chatTest.leave()'); await pause(500)
  await assert.rejects(run(0,`window.chatTest.send('Gone',${JSON.stringify(tokens[1].identity)})`), /left the room/)
  console.log('PASS Sending a whisper to a departed recipient fails visibly')
  assert.equal((await snapshot(1)).roomLosses,0)
  await client.removeParticipant(roomName,tokens[0].identity)
  for (let attempt=0; attempt<30; attempt++) {
    if ((await snapshot(0)).roomLosses===1) break
    await pause(100)
  }
  assert.equal((await snapshot(0)).roomLosses,1)
  assert.equal((await snapshot(0)).connection,'offline')
  console.log('PASS Unexpected server disconnect emits room loss; intentional leave does not')
  console.log('All LiveKit chat delivery checks passed')
  await finish(0)
}).catch(error => { console.error(error.message); void finish(1) })
