// Production chat UI with a deterministic transport, including unread and failure paths.
const { app, BrowserWindow } = require('electron')
const { build } = require('esbuild')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname, '..')
const output = path.join(root, 'release', 'chat-review')
const temp = require('node:fs').mkdtempSync(path.join(os.tmpdir(), 'zodiak-chat-ui-'))
app.setPath('userData', path.join(temp, 'profile'))
app.setPath('sessionData', path.join(temp, 'session'))
let win
const errors = []
const run = code => win.webContents.executeJavaScript(code, true)
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
const click = async selector => { await run(`document.querySelector(${JSON.stringify(selector)}).click()`); await pause(80) }
const check = async (code, label) => { if (!await run(code)) throw Error(label); console.log('PASS ' + label) }
const shot = async name => { await pause(180); await fs.writeFile(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()) }
const timeout = setTimeout(() => { console.error('Chat UI test timed out'); app.exit(1) }, 60000)
app.whenReady().then(async () => {
  await fs.mkdir(output, { recursive: true })
  await build({ entryPoints: [path.join(root, 'src/renderer/src/main.ts')], bundle: true, format: 'esm', outfile: path.join(temp, 'main.js'), plugins: [{ name: 'test-session', setup(build) { build.onResolve({ filter: /^\.\/session$/ }, () => ({ path: path.join(root, 'tests/ui-session.ts') })) } }] })
  const html = (await fs.readFile(path.join(root, 'src/renderer/index.html'), 'utf8')).replace('/src/styles.css', './styles.css').replace('/src/main.ts', './main.js').replace('src="/logo.svg"', 'src="./logo.svg"')
  await fs.writeFile(path.join(temp, 'index.html'), html)
  await fs.copyFile(path.join(root, 'src/renderer/src/styles.css'), path.join(temp, 'styles.css'))
  await fs.copyFile(path.join(root, 'build/logo.svg'), path.join(temp, 'logo.svg'))
  win = new BrowserWindow({ width: 1360, height: 860, show: false, frame: false, webPreferences: { preload: path.join(root, 'tests/ui-preload.cjs'), contextIsolation: true, sandbox: false, backgroundThrottling: false, offscreen: true } })
  win.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message) })
  await win.loadFile(path.join(temp, 'index.html')); await pause(350)
  // Simulate a focused visible app; the test window is rendered offscreen.
  await run(`Object.defineProperty(document, 'hasFocus', {value: () => true}); Object.defineProperty(document, 'visibilityState', {value: 'visible', configurable: true}); void 0`)
  await check(`document.querySelector('#chat-toggle').hidden && document.querySelector('#chat-panel').hidden`, 'Lobby has no chat')
  await run(`window.uiTest.holdJoin=true; window.joinFrames=[]; window.joinFrameWatcher=()=>{window.joinFrames.push({inRoom:document.body.classList.contains('in-room'),headerHidden:document.querySelector('#stage-head').hidden,chatHidden:document.querySelector('#chat-panel').hidden,sidebarHidden:document.querySelector('#room-sidebar').hidden}); if(window.uiTest.holdJoin) requestAnimationFrame(window.joinFrameWatcher)}; requestAnimationFrame(window.joinFrameWatcher); void 0`)
  await click('.room[title="after-hours"]'); await pause(150)
  await check(`window.uiTest.joinInFlight && window.joinFrames.length>=3 && window.joinFrames.every(frame=>!frame.inRoom && frame.headerHidden && frame.chatHidden && frame.sidebarHidden) && document.querySelector('#stage-wrap').getBoundingClientRect().width===document.querySelector('#room-workspace').getBoundingClientRect().width`, 'Every pending join frame stays in the complete lobby layout')
  await run(`window.uiTest.emitChat({text:'Arrived during join'})`)
  await check(`!document.querySelector('.chat-message-text')`, 'Messages arriving during join stay buffered until the room is ready')
  await shot('00-joining-lobby')
  await run(`window.uiTest.finishJoin()`); await pause(100)
  await check(`document.body.classList.contains('in-room') && document.querySelector('#room-title').textContent==='after-hours' && !document.querySelector('#stage-head').hidden && !document.querySelector('#room-sidebar').hidden && !document.querySelector('#chat-panel').hidden && document.querySelectorAll('.participant-tile').length===3 && document.querySelector('#chat-messages').textContent.includes('Arrived during join') && !document.querySelector('#chat-input').disabled`, 'Ready room presents header, roster, controls, and buffered chat together')
  await click('#leave')
  await run(`window.uiTest.holdJoin=true; window.uiTest.failJoin=true`)
  await click('.room[title="after-hours"]'); await run(`window.uiTest.finishJoin()`); await pause(100)
  await check(`!document.body.classList.contains('in-room') && document.querySelector('#stage-head').hidden && document.querySelector('#room-sidebar').hidden && document.querySelector('#chat-panel').hidden && !document.querySelector('#stage-note').hidden`, 'Failed join keeps a coherent lobby and reports its error')
  await run(`window.uiTest.failJoin=false`)
  await click('.room'); await pause(120)
  await check(`!document.querySelector('#chat-panel').hidden && document.querySelector('#room-workspace').dataset.chatPosition==='right' && document.querySelectorAll('[role=tab]').length===1 && !document.querySelector('.chat-tab-close')`, 'Room opens with a permanent right-docked room tab')
  await run(`window.uiTest.emitChat({text:'First message'}); window.uiTest.emitChat({text:'Second message'}); window.uiTest.emitChat({senderId:'jo',senderName:'Jordan Lee',text:'Another sender'}); window.uiTest.emitChat({text:'A new group'})`)
  await check(`document.querySelectorAll('.chat-message-group').length===3 && document.querySelectorAll('.chat-message-text').length===4 && document.querySelectorAll('.chat-message-head time').length===3`, 'Consecutive messages group by sender with one avatar/name/time header')
  await shot('01-room-chat-right')
  await click('#chat-toggle'); await run(`window.uiTest.emitChat({text:'No preview by default'})`)
  await check(`!document.querySelector('.chat-bubble') && document.querySelector('#chat-toggle .chat-badge').textContent==='1'`, 'Bubbles are opt-in while hidden messages still count')
  await click('#chat-toggle')
  await run(`window.uiTest.emitChat({text:'<img src=x onerror=alert(1)> https://example.com/test?x=1&y=2 www.example.org.'})`)
  await check(`document.querySelectorAll('.chat-message-text a').length===2 && !document.querySelector('.chat-message-text img') && document.querySelector('.chat-message-text a').target==='_blank'`, 'Message HTML is inert and HTTP links are clickable')
  await run(`window.uiTest.emitChat({text:'https://youtu.be/dQw4w9WgXcQ'})`)
  await check(`document.querySelector('.chat-embed-preview') && !document.querySelector('#chat-panel iframe')`, 'Supported video links have a click-to-load embed')
  await run(`window.uiTest.emitChat({text:'www.youtube.com/watch?v=dQw4w9WgXcQ'})`)
  await click('[data-whisper="sam"]')
  await check(`document.querySelectorAll('[role=tab]').length===2 && document.querySelector('[aria-selected=true]').dataset.tabId==='sam' && !document.querySelector('.chat-message-text')`, 'Whisper opens a separate empty private tab')
  await run(`document.querySelector('#chat-input').value='A private message'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-form').requestSubmit()`); await pause(100)
  await check(`window.uiTest.sentMessages[0].recipient==='sam' && document.querySelector('.chat-message-text').textContent==='A private message'`, 'Private composer targets only that participant')
  await run(`window.uiTest.emitChat({recipient:'me',text:'Private reply'}); window.uiTest.emitChat({text:'Public while private'})`)
  await check(`document.querySelectorAll('.chat-message-text').length===2 && document.querySelector('[data-tab-id=room] .chat-badge').textContent==='1'`, 'Incoming private replies stay isolated and inactive room tab counts unread')
  await run(`document.querySelector('#chat-input').value='Draft for Sam'; document.querySelector('#chat-input').dispatchEvent(new Event('input'))`)
  await click('[data-tab-id=room]')
  await check(`document.querySelector('#chat-input').value==='' && !document.querySelector('[data-tab-id=room] .chat-badge')`, 'Reading a tab clears its unread count and keeps drafts separate')
  await click('[data-tab-id=sam]')
  await check(`document.querySelector('#chat-input').value==='Draft for Sam'`, 'Switching tabs restores the private draft')
  await shot('02-private-chat')
  await click('[aria-label="Close whisper with Sam Rivera"]')
  await check(`document.querySelectorAll('[role=tab]').length===1 && document.querySelector('[aria-selected=true]').dataset.tabId==='room'`, 'Only whisper tabs can be closed')
  await click('[data-settings]')
  await click('#chat-position-bottom')
  await run(`document.querySelector('#show-chat-bubbles').checked=true`)
  await click('#save-settings')
  await check(`document.querySelector('#room-workspace').dataset.chatPosition==='bottom' && document.querySelector('#chat-panel').getBoundingClientRect().top >= document.querySelector('#stage-wrap').getBoundingClientRect().bottom-1`, 'Settings save bottom docking')
  await shot('03-room-chat-bottom')
  await click('[data-settings]'); await click('#chat-position-right'); await click('[data-close="settings-dialog"]')
  await check(`document.querySelector('#room-workspace').dataset.chatPosition==='bottom' && document.querySelector('#chat-position-bottom').getAttribute('aria-pressed')==='true'`, 'Canceling settings keeps the saved chat placement')
  await click('#chat-toggle')
  await run(`for(let n=0;n<101;n++) window.uiTest.emitChat({text:'Unread '+n})`)
  await check(`document.querySelector('#chat-toggle .chat-badge').textContent==='+99' && document.querySelector('#chat-panel').hidden && document.querySelectorAll('.chat-bubble').length===2`, 'Hidden chat caps badge at +99 and displays at most two bubbles')
  await run(`window.uiTest.emitChat({senderId:'jo',senderName:'Jordan Lee',recipient:'me',text:'Whisper while watching'})`)
  await check(`document.querySelector('[data-whisper=jo] .chat-badge').textContent==='1' && document.querySelectorAll('[role=tab]').length===2`, 'A hidden incoming whisper opens its tab and badges the participant')
  await shot('04-hidden-chat-bubbles')
  await click('.chat-bubble:last-child')
  await check(`!document.querySelector('#chat-panel').hidden && document.querySelector('[aria-selected=true]').dataset.tabId==='jo' && !document.querySelector('.chat-bubble') && !document.querySelector('[data-whisper=jo] .chat-badge')`, 'Clicking a bubble opens its conversation and clears read private counts')
  await run(`window.uiTest.emitParticipants([{id:'me',name:'Alex Morgan',local:true},{id:'sam',name:'Sam Rivera',local:false}])`)
  await check(`document.querySelector('#chat-input').disabled && document.querySelector('#chat-input').placeholder==='This person has left'`, 'Disconnected private recipient cannot be sent a message')
  await click('[data-tab-id=room]')
  await run(`window.uiTest.failChat=true; document.querySelector('#chat-input').value='Retry me'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-form').requestSubmit()`); await pause(120)
  await check(`document.querySelector('#chat-input').value==='Retry me' && !document.querySelector('#chat-error').hidden && !document.querySelector('#chat-input').disabled`, 'Failed send preserves draft and allows retry')
  await run(`window.uiTest.failChat=false; document.querySelector('#chat-form').requestSubmit()`); await pause(100)
  await check(`document.querySelector('#chat-input').value==='' && document.querySelector('#chat-error').hidden`, 'Retry succeeds without losing the message')
  await run(`document.querySelector('#chat-messages').scrollTop=0; document.querySelector('#chat-messages').dispatchEvent(new Event('scroll')); window.uiTest.emitChat({text:'Keep reading history'})`)
  await check(`document.querySelector('#chat-messages').scrollTop===0 && !document.querySelector('#chat-jump').hidden && document.querySelector('#chat-jump .chat-badge').textContent==='1'`, 'New messages preserve the reader scroll position and offer a jump control')
  await click('#chat-jump')
  await check(`document.querySelector('#chat-jump').hidden && !document.querySelector('[data-tab-id=room] .chat-badge')`, 'Jumping to the latest messages clears unread')
  await run(`document.querySelector('#chat-input').value='Typing'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true})); document.querySelector('#chat-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true}))`)
  await check(`document.querySelector('#chat-input').value==='Typing'`, 'Composition and Shift+Enter do not send prematurely')
  await click('[data-settings]'); await click('#chat-position-right'); await click('#save-settings')
  win.setSize(920,640); await pause(200)
  await check(`document.documentElement.scrollWidth<=innerWidth && document.querySelector('#chat-panel').getBoundingClientRect().right<=innerWidth && document.querySelector('#stage-wrap').getBoundingClientRect().right <= document.querySelector('#chat-panel').getBoundingClientRect().left+1`, 'Chat fits a compact window without covering streams or call controls')
  await shot('05-chat-small')
  await run(`document.body.classList.add('theater')`)
  await check(`getComputedStyle(document.querySelector('#chat-focus-toggle')).display==='flex'`, 'Focus view keeps an accessible chat toggle')
  await click('#chat-focus-toggle')
  await check(`document.querySelector('#chat-panel').hidden`, 'Focus toggle hides the chat')
  await run(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'C',ctrlKey:true,shiftKey:true,bubbles:true})); document.body.classList.remove('theater')`)
  await check(`!document.querySelector('#chat-panel').hidden`, 'Keyboard shortcut restores the chat')
  await click('#chat-toggle'); await run(`window.uiTest.emitChat({text:'Temporary preview'})`); await pause(5300)
  await check(`!document.querySelector('.chat-bubble')`, 'Bubbles expire after five seconds')
  await click('#leave')
  await check(`document.querySelector('#chat-toggle').hidden && document.querySelector('#chat-panel').hidden && !document.querySelector('.chat-message-text') && !document.querySelector('.chat-bubble')`, 'Leaving detaches chat and previews while retaining room history')
  await run(`window.uiTest.emitChat({text:'Away message must not replay'})`)
  await click('.room')
  await check(`document.querySelectorAll('[role=tab]').length===2 && document.querySelector('#chat-messages').textContent.includes('First message') && !document.querySelector('#chat-messages').textContent.includes('Away message must not replay') && document.querySelector('#chat-input').value==='Typing'`, 'Rejoining restores received room history, open whispers, and drafts without replaying away messages')
  await click('#chat-toggle')
  await click('[data-tab-id=jo]')
  await check(`document.querySelector('#chat-messages').textContent.includes('Whisper while watching') && !document.querySelector('#chat-messages').textContent.includes('First message')`, 'Whisper history survives leaving and stays separate from public chat')
  await click('[data-tab-id=room]')
  await run(`window.uiTest.holdJoin=true`)
  await click('.room[title="watch-party"]')
  await check(`document.querySelector('#room-title').textContent==='the-lounge' && document.querySelector('#chat-messages').textContent.includes('First message') && document.querySelector('#chat-input').disabled && document.querySelector('#room-workspace').inert`, 'Switching rooms keeps the previous view coherent and prevents actions against the incoming session')
  await run(`window.uiTest.emitChat({text:'Buffered for room two'}); window.uiTest.finishJoin()`); await pause(100)
  await check(`document.querySelectorAll('[role=tab]').length===1 && document.querySelector('#chat-messages').textContent.includes('Buffered for room two') && !document.querySelector('#chat-messages').textContent.includes('First message') && document.querySelector('#chat-input').value==='' && !document.querySelector('#room-workspace').inert`, 'The next room commits its own buffered chat and restores interactions')
  await run(`window.uiTest.emitChat({text:'Only in room two'})`)
  await click('.room[title="the-lounge"]')
  await check(`document.querySelector('#chat-messages').textContent.includes('First message') && !document.querySelector('#chat-messages').textContent.includes('Only in room two') && document.querySelector('#chat-input').value==='Typing'`, 'Switching back restores room one without mixing room two history')
  await click('.room[title="watch-party"]')
  await check(`document.querySelector('#chat-messages').textContent.includes('Only in room two') && !document.querySelector('#chat-messages').textContent.includes('First message')`, 'Room two also retains its history across switches')
  await run(`window.uiTest.hooks.onConnection('reconnecting')`)
  await check(`!document.querySelector('.chat-message-text') && document.querySelector('#chat-input').disabled`, 'Losing the live connection clears the active chat')
  await run(`window.uiTest.hooks.onConnection('connected')`)
  await click('.room[title="the-lounge"]')
  await check(`document.querySelectorAll('[role=tab]').length===1 && !document.querySelector('.chat-message-text') && document.querySelector('#chat-input').value===''`, 'Connection loss also clears rooms and whispers cached earlier')
  await run(`window.uiTest.emitChat({text:'Before terminal disconnect'}); window.uiTest.hooks.onRoomLost(); window.uiTest.hooks.onConnection('offline')`)
  await check(`!document.querySelector('.chat-message-text') && document.querySelector('#chat-input').disabled`, 'Unexpected terminal disconnect clears history')
  await run(`window.uiTest.hooks.onConnection('connected'); window.uiTest.emitChat({text:'Before lobby outage'})`)
  await click('#leave')
  await run(`window.sharescreen.setTestServerAvailable(false)`)
  await click('#server-settings'); await click('#save-server-settings')
  await run(`window.sharescreen.setTestServerAvailable(true)`)
  await click('#server-settings'); await click('#save-server-settings'); await click('.room[title="the-lounge"]')
  await check(`!document.querySelector('.chat-message-text')`, 'Server failure while in the lobby clears cached room history')
  await run(`window.uiTest.emitChat({text:'First server only'})`)
  await click('#leave')
  await click('#server-settings'); await run(`document.querySelector('#server-url').value='ws://other-server:7880'`); await click('#save-server-settings'); await click('.room[title="the-lounge"]')
  await check(`!document.querySelector('.chat-message-text')`, 'The same room name on another server has separate history')
  await run(`window.uiTest.emitChat({text:'Second server only'})`)
  await click('#leave')
  await click('#server-settings'); await run(`document.querySelector('#server-url').value='ws://localhost:7880'`); await click('#save-server-settings'); await click('.room[title="the-lounge"]')
  await check(`document.querySelector('#chat-messages').textContent.includes('First server only') && !document.querySelector('#chat-messages').textContent.includes('Second server only')`, 'Returning to the original server restores only its room history')
  await win.reload(); await pause(350); await click('.room[title="the-lounge"]')
  await check(`!document.querySelector('.chat-message-text') && document.querySelectorAll('[role=tab]').length===1`, 'Restarting the renderer starts with empty history because nothing is persisted')
  if (errors.length) throw Error(errors.join('\n'))
  console.log('All chat UI checks passed. Screenshots: ' + output)
  clearTimeout(timeout); win.destroy(); app.exit(0)
}).catch(error => { console.error(error); clearTimeout(timeout); win?.destroy(); app.exit(1) })
