// Production chat UI with a deterministic transport, including unread and failure paths.
const { app, BrowserWindow } = require('./silent-electron.cjs')
const { build } = require('./build-renderer.cjs')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname, '..')
const output = path.join(root, 'release', 'chat-review')
const temp = require('node:fs').mkdtempSync(path.join(os.tmpdir(), 'zodiak-chat-ui-'))
app.setPath('userData', path.join(temp, 'profile'))
app.setPath('sessionData', path.join(temp, 'session'))
let win
const errors = []
const run = code => win.webContents.executeJavaScript(code, true)
const runAsync = code => run(`(async () => { ${code} })()`)
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
const click = async selector => { await run(`document.querySelector(${JSON.stringify(selector)}).click()`); await pause(80) }
const rightClick = async selector => {
  const point = await run(`(()=>{const rect=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:Math.round(rect.left+rect.width/2),y:Math.round(rect.top+rect.height/2)}})()`)
  win.webContents.sendInputEvent({type:'mouseDown',...point,button:'right',clickCount:1}); win.webContents.sendInputEvent({type:'mouseUp',...point,button:'right',clickCount:1}); await pause(100)
}
const check = async (code, label) => { if (!await run(code)) throw Error(label); console.log('PASS ' + label) }
const shot = async name => { await pause(180); await fs.writeFile(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()) }
const timeout = setTimeout(() => { console.error('Chat UI test timed out'); app.exit(1) }, 60000)
app.whenReady().then(async () => {
  await fs.mkdir(output, { recursive: true })
  // Initialize fixture controls before the deliberately deferred production
  // transport so this test can hold/fail the very first room connection.
  await build({ stdin: { contents: "import './tests/ui-session.ts'; import './src/renderer/src/main.ts'", resolveDir: root, loader: 'ts' }, bundle: true, format: 'esm', outfile: path.join(temp, 'main.js'), plugins: [{ name: 'test-session', setup(build) { build.onResolve({ filter: /^\.\/session$/ }, () => ({ path: path.join(root, 'tests/ui-session.ts') })) } }] })
  const html = (await fs.readFile(path.join(root, 'src/renderer/index.html'), 'utf8')).replace('/src/styles.css', './styles.css').replace('/src/main.ts', './main.js').replaceAll('src="/logo.svg"', 'src="./logo.svg"')
  await fs.writeFile(path.join(temp, 'index.html'), html)
  await fs.copyFile(path.join(root, 'src/renderer/src/styles.css'), path.join(temp, 'styles.css'))
  await fs.copyFile(path.join(root, 'build/logo.svg'), path.join(temp, 'logo.svg'))
  win = new BrowserWindow({ width: 1360, height: 860, show: false, frame: false, webPreferences: { preload: path.join(root, 'tests/ui-preload.cjs'), contextIsolation: true, sandbox: false, backgroundThrottling: false, offscreen: true } })
  win.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message) })
  await win.loadFile(path.join(temp, 'index.html')); await pause(350)
  // Simulate a focused visible app; the test window is rendered offscreen.
  await run(`Object.defineProperty(document, 'hasFocus', {value: () => true}); Object.defineProperty(document, 'visibilityState', {value: 'visible', configurable: true}); void 0`)
  await check(`document.querySelector('#chat-toggle').hidden && document.querySelector('#chat-panel').hidden`, 'Lobby has no chat')
  await run(`window.uiTest.holdJoin=true; window.joinFrames=[]; window.joinFrameWatcher=()=>{window.joinFrames.push({inRoom:document.body.classList.contains('in-room'),headerHidden:document.querySelector('#stage-head').hidden,chatHidden:document.querySelector('#chat-panel').hidden,sidebarHidden:document.querySelector('#room-sidebar').hidden}); if(window.uiTest.holdJoin) requestAnimationFrame(window.joinFrameWatcher)}; requestAnimationFrame(window.joinFrameWatcher); void 0`)
  await click('.room[title="after-hours"]'); await pause(150)
  await check(`window.uiTest.joinInFlight && window.joinFrames.length>=3 && window.joinFrames.every(frame=>!frame.inRoom && frame.headerHidden && frame.chatHidden && frame.sidebarHidden) && document.querySelector('#stage-wrap').getBoundingClientRect().width===document.querySelector('#room-workspace').getBoundingClientRect().width`, 'Every pending join frame stays in the complete lobby layout')
  await run(`window.uiTest.emitChat({text:'Arrived during join'})`)
  await check(`!document.querySelector('.chat-message-text')`, 'Messages arriving during join stay buffered until the room is ready')
  await shot('00-joining-lobby')
  await run(`window.uiTest.finishJoin()`); await pause(100)
  await check(`document.body.classList.contains('in-room') && document.querySelector('#room-title').textContent==='after-hours' && !document.querySelector('#stage-head').hidden && !document.querySelector('#room-sidebar').hidden && document.querySelector('#chat-panel').hidden && document.querySelectorAll('.participant-tile').length===3 && document.querySelector('#chat-toggle .chat-badge').textContent==='1' && !document.querySelector('#chat-input').disabled`, 'Ready room presents header, roster, controls, and buffered unread chat with chat initially hidden')
  await click('#chat-toggle')
  await check(`document.querySelector('#chat-messages').textContent.includes('Arrived during join')`, 'Opening initially hidden chat displays the buffered message')
  await click('#chat-toggle')
  await click('#leave')
  await run(`window.uiTest.holdJoin=true; window.uiTest.failJoin=true`)
  await click('.room[title="after-hours"]'); await run(`window.uiTest.finishJoin()`); await pause(100)
  await check(`!document.body.classList.contains('in-room') && document.querySelector('#stage-head').hidden && document.querySelector('#room-sidebar').hidden && document.querySelector('#chat-panel').hidden && !document.querySelector('#stage-note').hidden`, 'Failed join keeps a coherent lobby and reports its error')
  await run(`window.uiTest.failJoin=false`)
  await click('.room'); await pause(120)
  await check(`document.querySelector('#chat-panel').hidden && document.querySelector('#chat-toggle').getAttribute('aria-expanded')==='false' && !document.querySelector('#chat-toggle').hidden && document.querySelector('#room-workspace').dataset.chatPosition==='right' && document.querySelectorAll('#chat-tabs [role=tab]').length===1 && !document.querySelector('.chat-tab-close')`, 'Room starts with right-docked chat hidden and its toggle available')
  await click('#chat-toggle')
  await run(`window.uiTest.emitChat({text:'First message'}); window.uiTest.emitChat({text:'Second message'}); window.uiTest.emitChat({senderId:'jo',senderName:'Jordan Lee',text:'Another sender'}); window.uiTest.emitChat({text:'A new group'})`)
  await check(`document.querySelectorAll('.chat-message-group').length===3 && document.querySelectorAll('.chat-message-text').length===4 && document.querySelectorAll('.chat-message-head time').length===3`, 'Consecutive messages group by sender with one avatar/name/time header')
  await shot('01-room-chat-right')
  await click('#chat-toggle'); await run(`window.uiTest.emitChat({text:'No preview by default'})`)
  await check(`!document.querySelector('.chat-bubble') && document.querySelector('#chat-toggle .chat-badge').textContent==='1'`, 'Bubbles are opt-in while hidden messages still count')
  await click('#chat-toggle')
  await run(`window.uiTest.emitChat({text:'<img src=x onerror=alert(1)> https://example.com/test?x=1&y=2 www.example.org.'})`)
  await check(`document.querySelectorAll('.chat-message-text a').length===2 && !document.querySelector('.chat-message-text img') && document.querySelector('.chat-message-text a').target==='_blank'`, 'Message HTML is inert and HTTP links are clickable')
  await run(`window.uiTest.emitChat({text:'https://youtu.be/dQw4w9WgXcQ'})`)
  await check(`document.querySelector('.chat-embed-preview') && !document.querySelector('#chat-panel iframe')`, 'Supported video links have a click-to-load embed')
  await run(`window.uiTest.emitChat({text:'www.youtube.com/watch?v=dQw4w9WgXcQ'})`)
  await click('[data-whisper="sam"]')
  await check(`document.querySelectorAll('#chat-tabs [role=tab]').length===2 && document.querySelector('#chat-tabs [aria-selected=true]').dataset.tabId==='sam' && !document.querySelector('.chat-message-text')`, 'Whisper opens a separate empty private tab')
  await run(`document.querySelector('#chat-input').value='A private message'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-form').requestSubmit()`); await pause(100)
  await check(`window.uiTest.sentMessages[0].recipient==='sam' && document.querySelector('.chat-message-text').textContent==='A private message'`, 'Private composer targets only that participant')
  await run(`window.uiTest.emitChat({recipient:'me',text:'Private reply'}); window.uiTest.emitChat({text:'Public while private'})`)
  await check(`document.querySelectorAll('.chat-message-text').length===2 && document.querySelector('[data-tab-id=room] .chat-badge').textContent==='1'`, 'Incoming private replies stay isolated and inactive room tab counts unread')
  await run(`document.querySelector('#chat-input').value='Draft for Sam'; document.querySelector('#chat-input').dispatchEvent(new Event('input'))`)
  await click('[data-tab-id=room]')
  await check(`document.querySelector('#chat-input').value==='' && !document.querySelector('[data-tab-id=room] .chat-badge')`, 'Reading a tab clears its unread count and keeps drafts separate')
  await click('[data-tab-id=sam]')
  await check(`document.querySelector('#chat-input').value==='Draft for Sam'`, 'Switching tabs restores the private draft')
  await shot('02-private-chat')
  await click('[aria-label="Close whisper with Sam Rivera"]')
  await check(`document.querySelectorAll('#chat-tabs [role=tab]').length===1 && document.querySelector('#chat-tabs [aria-selected=true]').dataset.tabId==='room'`, 'Only whisper tabs can be closed')
  await click('[data-settings]')
  await click('#settings-tab-interface')
  await run(`document.querySelector('#show-chat-bubbles').checked=true`)
  await click('#save-settings')
  await check(`document.querySelector('#room-workspace').dataset.chatPosition==='right' && !document.querySelector('[id^=chat-position]')`, 'Chat stays right-docked and legacy bottom placement has no setting')
  await shot('03-room-chat-right')
  await click('[data-settings]'); await click('#settings-tab-interface'); await click('#show-chat-bubbles'); await click('[data-close="settings-dialog"]')
  await check(`document.querySelector('#room-workspace').dataset.chatPosition==='right' && document.querySelector('#show-chat-bubbles').checked`, 'Canceling settings keeps saved chat bubbles and right placement')
  await click('#chat-toggle')
  await run(`for(let n=0;n<101;n++) window.uiTest.emitChat({text:'Unread '+n})`)
  await check(`document.querySelector('#chat-toggle .chat-badge').textContent==='+99' && document.querySelector('#chat-panel').hidden && document.querySelectorAll('.chat-bubble').length===2`, 'Hidden chat caps badge at +99 and displays at most two bubbles')
  await run(`window.uiTest.emitChat({senderId:'jo',senderName:'Jordan Lee',recipient:'me',text:'Whisper while watching'})`)
  await check(`document.querySelector('[data-whisper=jo] .chat-badge').textContent==='1' && document.querySelectorAll('#chat-tabs [role=tab]').length===2`, 'A hidden incoming whisper opens its tab and badges the participant')
  await shot('04-hidden-chat-bubbles')
  await click('.chat-bubble:last-child')
  await check(`!document.querySelector('#chat-panel').hidden && document.querySelector('#chat-tabs [aria-selected=true]').dataset.tabId==='jo' && !document.querySelector('.chat-bubble') && !document.querySelector('[data-whisper=jo] .chat-badge')`, 'Clicking a bubble opens its conversation and clears read private counts')
  await run(`window.uiTest.emitParticipants([{id:'me',name:'Alex Morgan',local:true},{id:'sam',name:'Sam Rivera',local:false}])`)
  await check(`document.querySelector('#chat-input').disabled && document.querySelector('#chat-input').placeholder==='This person has left'`, 'Disconnected private recipient cannot be sent a message')
  await click('[data-tab-id=room]')
  await run(`window.uiTest.failChat=true; document.querySelector('#chat-input').value='Retry me'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-form').requestSubmit()`); await pause(120)
  await check(`document.querySelector('#chat-input').value==='Retry me' && !document.querySelector('#chat-error').hidden && !document.querySelector('#chat-input').disabled`, 'Failed send preserves draft and allows retry')
  await run(`window.uiTest.failChat=false; document.querySelector('#chat-form').requestSubmit()`); await pause(100)
  await check(`document.querySelector('#chat-input').value==='' && document.querySelector('#chat-error').hidden`, 'Retry succeeds without losing the message')
  await run(`document.querySelector('#chat-messages').scrollTop=0; document.querySelector('#chat-messages').dispatchEvent(new Event('scroll')); window.uiTest.emitChat({text:'Keep reading history'})`)
  await check(`document.querySelector('#chat-messages').scrollTop===0 && !document.querySelector('#chat-jump').hidden && document.querySelector('#chat-jump .chat-badge').textContent==='1'`, 'New messages preserve the reader scroll position and offer a jump control')
  await click('#chat-jump')
  await check(`document.querySelector('#chat-jump').hidden && !document.querySelector('[data-tab-id=room] .chat-badge')`, 'Jumping to the latest messages clears unread')
  await run(`document.querySelector('#chat-input').value='Typing'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true})); document.querySelector('#chat-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true}))`)
  await check(`document.querySelector('#chat-input').value==='Typing'`, 'Composition and Shift+Enter do not send prematurely')
  win.setSize(920,640); await pause(200)
  await check(`document.documentElement.scrollWidth<=innerWidth && document.querySelector('#chat-panel').getBoundingClientRect().right<=innerWidth && document.querySelector('#stage-wrap').getBoundingClientRect().right <= document.querySelector('#chat-panel').getBoundingClientRect().left+1`, 'Chat fits a compact window without covering streams or call controls')
  await shot('05-chat-small')
  await run(`document.body.classList.add('theater')`)
  await check(`getComputedStyle(document.querySelector('#chat-focus-toggle')).display==='flex'`, 'Focus view keeps an accessible chat toggle')
  await click('#chat-focus-toggle')
  await check(`document.querySelector('#chat-panel').hidden`, 'Focus toggle hides the chat')
  await run(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'C',ctrlKey:true,shiftKey:true,bubbles:true})); document.body.classList.remove('theater')`)
  await check(`!document.querySelector('#chat-panel').hidden`, 'Keyboard shortcut restores the chat')
  await click('#chat-toggle'); await run(`window.uiTest.emitChat({text:'Temporary preview'})`); await pause(5300)
  await check(`!document.querySelector('.chat-bubble')`, 'Bubbles expire after five seconds')
  await click('#leave')
  await check(`document.querySelector('#chat-toggle').hidden && document.querySelector('#chat-panel').hidden && !document.querySelector('.chat-message-text') && !document.querySelector('.chat-bubble')`, 'Leaving detaches chat and previews while retaining room history')
  await run(`window.uiTest.emitChat({text:'Away message must not replay'})`)
  await click('.room')
  await check(`document.querySelectorAll('#chat-tabs [role=tab]').length===2 && document.querySelector('#chat-messages').textContent.includes('First message') && !document.querySelector('#chat-messages').textContent.includes('Away message must not replay') && document.querySelector('#chat-input').value==='Typing'`, 'Rejoining restores received room history, open whispers, and drafts without replaying away messages')
  await click('#chat-toggle')
  await click('[data-tab-id=jo]')
  await check(`document.querySelector('#chat-messages').textContent.includes('Whisper while watching') && !document.querySelector('#chat-messages').textContent.includes('First message')`, 'Whisper history survives leaving and stays separate from public chat')
  await click('[data-tab-id=room]')
  await run(`window.uiTest.holdJoin=true`)
  await click('.room[title="watch-party"]')
  await check(`document.querySelector('#room-title').textContent==='the-lounge' && document.querySelector('#chat-messages').textContent.includes('First message') && document.querySelector('#chat-input').disabled && document.querySelector('#room-workspace').inert`, 'Switching rooms keeps the previous view coherent and prevents actions against the incoming session')
  await run(`window.uiTest.emitChat({text:'Buffered for room two'}); window.uiTest.finishJoin()`); await pause(100)
  await check(`document.querySelectorAll('#chat-tabs [role=tab]').length===1 && document.querySelector('#chat-messages').textContent.includes('Buffered for room two') && !document.querySelector('#chat-messages').textContent.includes('First message') && document.querySelector('#chat-input').value==='' && !document.querySelector('#room-workspace').inert`, 'The next room commits its own buffered chat and restores interactions')
  await run(`window.uiTest.emitChat({text:'Only in room two'})`)
  await click('.room[title="the-lounge"]')
  await check(`document.querySelector('#chat-messages').textContent.includes('First message') && !document.querySelector('#chat-messages').textContent.includes('Only in room two') && document.querySelector('#chat-input').value==='Typing'`, 'Switching back restores room one without mixing room two history')
  await click('.room[title="watch-party"]')
  await check(`document.querySelector('#chat-messages').textContent.includes('Only in room two') && !document.querySelector('#chat-messages').textContent.includes('First message')`, 'Room two also retains its history across switches')
  await run(`window.uiTest.hooks.onConnection('reconnecting')`)
  await check(`!document.querySelector('.chat-message-text') && document.querySelector('#chat-input').disabled`, 'Losing the live connection clears the active chat')
  await run(`window.uiTest.hooks.onConnection('connected')`)
  await click('.room[title="the-lounge"]')
  await check(`document.querySelectorAll('#chat-tabs [role=tab]').length===1 && !document.querySelector('.chat-message-text') && document.querySelector('#chat-input').value===''`, 'Connection loss also clears rooms and whispers cached earlier')
  await run(`window.uiTest.emitChat({text:'Before terminal disconnect'}); window.uiTest.hooks.onRoomLost(); window.uiTest.hooks.onConnection('offline')`)
  await check(`!document.querySelector('.chat-message-text') && document.querySelector('#chat-input').disabled`, 'Unexpected terminal disconnect clears history')
  await run(`window.uiTest.hooks.onConnection('connected'); window.uiTest.emitChat({text:'Before lobby outage'})`)
  await click('#leave')
  await run(`window.sharescreen.setTestServerAvailable(false)`)
  await click('#server-settings'); await click('#save-server-settings')
  await run(`window.sharescreen.setTestServerAvailable(true)`)
  await click('#server-settings'); await click('#save-server-settings'); await click('.room[title="the-lounge"]')
  await check(`!document.querySelector('.chat-message-text')`, 'Server failure while in the lobby clears cached room history')
  await run(`window.uiTest.emitChat({text:'First server only'})`)
  await click('#leave')
  await click('#server-settings'); await run(`document.querySelector('#server-url').value='ws://other-server:7880'`); await click('#save-server-settings'); await click('.room[title="the-lounge"]')
  await check(`!document.querySelector('.chat-message-text')`, 'The same room name on another server has separate history')
  await run(`window.uiTest.emitChat({text:'Second server only'})`)
  await click('#leave')
  await click('#server-settings'); await run(`document.querySelector('#server-url').value='ws://localhost:7880'`); await click('#save-server-settings'); await click('.room[title="the-lounge"]')
  await check(`document.querySelector('#chat-messages').textContent.includes('First server only') && !document.querySelector('#chat-messages').textContent.includes('Second server only')`, 'Returning to the original server restores only its room history')
  await win.reload(); await pause(350); await click('.room[title="the-lounge"]')
  await check(`!document.querySelector('.chat-message-text') && document.querySelectorAll('#chat-tabs [role=tab]').length===1`, 'Restarting the renderer starts with empty history because nothing is persisted')
  await check(`document.querySelector('#chat-panel').hidden`, 'Restarting the renderer restores the hidden chat default')
  await click('#chat-toggle')
  await runAsync(`window.testImage = async (name='photo.png') => {
    const canvas=document.createElement('canvas'); canvas.width=360; canvas.height=220;
    const ctx=canvas.getContext('2d'); ctx.fillStyle='#7565a8'; ctx.fillRect(0,0,360,220); ctx.fillStyle='#eeeef2'; ctx.font='24px sans-serif'; ctx.fillText('Image in chat',90,115);
    return new File([await new Promise(resolve=>canvas.toBlob(resolve))],name,{type:'image/png'});
  }; window.pasteFile=(...files)=>{const data=new DataTransfer();for(const file of files)data.items.add(file);document.querySelector('#chat-input').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))}; window.pickFile=async (...files)=>{
    const chooser=document.querySelector('#chat-file'); const click=chooser.click; let opened=false; chooser.click=()=>{opened=true}; document.querySelector('#chat-attach').click(); chooser.click=click;
    if(!opened) throw Error('Attachment button did not open file chooser'); const data=new DataTransfer();for(const file of files)data.items.add(file);chooser.files=data.files;chooser.dispatchEvent(new Event('change'));
  }; window.pasteFile(await window.testImage()); void 0`); await pause(180)
  await check(`!document.querySelector('#chat-attachment').hidden && document.querySelector('.chat-attachment-preview').naturalWidth===360 && !document.querySelector('#chat-send').disabled && window.uiTest.sentMessages.length===0`, 'Pasting an image shows a draft preview and enables image-only send without sending immediately')
  await check(`document.querySelector('#chat-attach').getBoundingClientRect().left < document.querySelector('#chat-input').getBoundingClientRect().left && document.querySelector('#chat-file').accept==='image/png,image/jpeg,image/gif,image/webp,image/avif'`, 'Attachment button sits left of the composer and file chooser accepts only supported images')
  await click('[data-whisper=sam]')
  await check(`document.querySelector('#chat-attachment').hidden`, 'Public image draft stays separate from private conversations')
  await click('[data-tab-id=room]')
  await check(`!document.querySelector('#chat-attachment').hidden`, 'Switching back restores the image draft')
  await run(`window.uiTest.failChat=true; document.querySelector('#chat-form').requestSubmit()`); await pause(100)
  await check(`!document.querySelector('#chat-attachment').hidden && !document.querySelector('#chat-error').hidden && !document.querySelector('#chat-send').disabled`, 'Failed image send preserves the attachment for retry')
  await run(`window.uiTest.failChat=false; document.querySelector('#chat-form').requestSubmit()`); await pause(180)
  await check(`document.querySelector('#chat-attachment').hidden && document.querySelector('.chat-image-attachment img').naturalWidth===360 && window.uiTest.sentMessages[0].text==='' && window.uiTest.sentMessages[0].images[0].size>0`, 'Image-only retry renders the image in the chat and clears its draft')
  await click('.chat-image-attachment')
  await check(`document.querySelector('#chat-image-dialog').open && document.querySelector('#chat-image-full').naturalWidth===360`, 'Clicking an attached image opens a full image viewer')
  await check(`!document.querySelector('#chat-image-actions, #chat-image-open, #chat-image-download, #chat-image-menu') && typeof window.sharescreen.chatImageAction==='undefined'`, 'Image viewer exposes no browser or download controls or API')
  await check(`!document.querySelector('#chat-image-close') && getComputedStyle(document.querySelector('#chat-image-dialog')).backgroundColor==='rgba(0, 0, 0, 0)' && getComputedStyle(document.querySelector('#chat-image-dialog')).borderTopWidth==='0px' && getComputedStyle(document.querySelector('#chat-image-dialog')).paddingTop==='0px' && (()=>{const image=getComputedStyle(document.querySelector('#chat-image-dialog'),'::backdrop');const settings=getComputedStyle(document.querySelector('#settings-dialog'),'::backdrop');return image.backgroundColor===settings.backgroundColor && image.backdropFilter===settings.backdropFilter && image.backdropFilter==='blur(7px)'})()`, 'Expanded image stays frameless with the same darkened, blurred backdrop as settings')
  await check(`(()=>{const rect=document.querySelector('#chat-image-full').getBoundingClientRect();return Math.abs(rect.left+rect.width/2-innerWidth/2)<1 && Math.abs(rect.top+rect.height/2-innerHeight/2)<1})()`, 'Expanded image is centered in the window')
  await check(`document.querySelector('#chat-image-previous').hidden && document.querySelector('#chat-image-next').hidden && document.querySelector('#chat-image-sequence').hidden`, 'Single-image messages have no sequence or navigation controls')
  await click('#chat-image-full')
  await check(`document.querySelector('#chat-image-dialog').open`, 'Clicking the image keeps the viewer open')
  await shot('07-expanded-image')
  win.webContents.sendInputEvent({type:'mouseDown',x:10,y:80,button:'left',clickCount:1}); win.webContents.sendInputEvent({type:'mouseUp',x:10,y:80,button:'left',clickCount:1}); await pause(100)
  await check(`!document.querySelector('#chat-image-dialog').open && !document.querySelector('#chat-image-full').hasAttribute('src')`, 'Clicking outside the image closes the viewer and releases its image URL')
  await run(`document.body.classList.add('theater')`); await click('.chat-image-attachment')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'}); win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'}); await pause(100)
  await check(`!document.querySelector('#chat-image-dialog').open && document.body.classList.contains('theater')`, 'Escape closes the image viewer while preserving focus view')
  await run(`document.body.classList.remove('theater')`)
  await rightClick('.chat-image-attachment img')
  await check(`!document.querySelector('#chat-image-menu')`, 'Right-clicking an attachment exposes no image action menu')
  await click('[data-tab-id=sam]')
  await runAsync(`await window.pickFile(await window.testImage('private.png')); void 0`); await pause(180)
  await run(`document.querySelector('#chat-input').value='Image caption'; document.querySelector('#chat-input').dispatchEvent(new Event('input')); document.querySelector('#chat-form').requestSubmit()`); await pause(180)
  await check(`window.uiTest.sentMessages.at(-1).recipient==='sam' && window.uiTest.sentMessages.at(-1).text==='Image caption' && document.querySelector('.chat-image-attachment img').naturalWidth===360 && document.querySelector('#chat-input').value===''`, 'File chooser sends image and caption to the private recipient')
  await runAsync(`await window.pickFile(await window.testImage('remove.png')); void 0`); await pause(180)
  await click('.chat-attachment-remove')
  await check(`document.querySelector('#chat-attachment').hidden && document.querySelector('#chat-send').disabled`, 'Removing an attachment cancels the image draft')
  for (const [expression,label] of [
    [`new File(['video'],'clip.mp4',{type:'video/mp4'})`,'Video attachments are rejected'],
    [`new File(['<svg/>'],'drawing.svg',{type:'image/svg+xml'})`,'SVG attachments are rejected'],
    [`new File(['not an image'],'fake.png',{type:'image/png'})`,'Renamed files with an image MIME type are rejected'],
    [`new File([new Uint8Array(10*1024*1024+1)],'large.png',{type:'image/png'})`,'Oversize images are rejected']
  ]) {
    await run(`window.pasteFile(${expression}); void 0`); await pause(120)
    await check(`document.querySelector('#chat-attachment').hidden && !document.querySelector('#chat-error').hidden`,label)
  }
  await runAsync(`window.pasteFile(await window.testImage('keep.png')); void 0`); await pause(180)
  await run(`window.pasteFile(new File(['wrong'],'fake.png',{type:'image/png'})); void 0`); await pause(100)
  await check(`!document.querySelector('#chat-attachment').hidden && document.querySelector('.chat-attachment-name').textContent==='keep.png'`, 'An invalid replacement preserves the previous valid image')
  await click('.chat-attachment-remove'); await click('[data-tab-id=room]')
  await runAsync(`await window.pickFile(...await Promise.all(['one.png','two.png','three.png'].map(name=>window.testImage(name)))); void 0`); await pause(180)
  await runAsync(`window.pasteFile(...await Promise.all(['four.png','five.png'].map(name=>window.testImage(name)))); void 0`); await pause(180)
  await check(`document.querySelector('#chat-file').multiple && document.querySelectorAll('.chat-attachment-item').length===5 && document.querySelector('.chat-attachment-count').textContent==='5 / 10'`, 'Multiple file selection and clipboard images append to the same draft')
  await click('.chat-attachment-item:nth-child(2) .chat-attachment-remove')
  await check(`[...document.querySelectorAll('.chat-attachment-name')].map(item=>item.textContent).join(',')==='one.png,three.png,four.png,five.png'`, 'Removing one preview preserves the other images and their order')
  await runAsync(`window.pasteFile(await window.testImage('valid.png'),new File([new Uint8Array(10*1024*1024+1)],'large.png',{type:'image/png'})); void 0`); await pause(180)
  await check(`document.querySelectorAll('.chat-attachment-item').length===4 && document.querySelector('#chat-error').textContent.includes('10 MB')`, 'A selection containing an oversized image preserves the draft without adding a partial selection')
  await runAsync(`await window.pickFile(...await Promise.all(Array.from({length:6},(_,i)=>window.testImage('extra-'+i+'.png')))); void 0`); await pause(180)
  await check(`document.querySelectorAll('.chat-attachment-item').length===10 && document.querySelector('.chat-attachment-count').textContent==='10 / 10'`, 'Ten image previews fit in a bounded scrollable draft tray')
  await shot('09-multiple-image-draft')
  await runAsync(`window.pasteFile(await window.testImage('eleventh.png')); void 0`); await pause(180)
  await check(`document.querySelectorAll('.chat-attachment-item').length===10 && document.querySelector('#chat-error').textContent.includes('10 images')`, 'An eleventh image is rejected without replacing any selected image')
  await click('[data-tab-id=sam]');await check(`document.querySelector('#chat-attachment').hidden`, 'Multi-image drafts remain isolated from whispers');await click('[data-tab-id=room]')
  await run(`window.batchSentBefore=window.uiTest.sentMessages.length;window.uiTest.failChat=true;document.querySelector('#chat-input').value='Ten images';document.querySelector('#chat-input').dispatchEvent(new Event('input'));document.querySelector('#chat-form').requestSubmit()`);await pause(100)
  await check(`document.querySelectorAll('.chat-attachment-item').length===10 && document.querySelector('#chat-input').value==='Ten images'`, 'Failed multi-image send preserves every image and its caption')
  await run(`window.uiTest.failChat=false;document.querySelector('#chat-form').requestSubmit()`);await pause(220)
  await check(`window.uiTest.sentMessages.length===window.batchSentBefore+1 && window.uiTest.sentMessages.at(-1).images.length===10 && window.uiTest.sentMessages.at(-1).text==='Ten images' && document.querySelector('#chat-attachment').hidden && document.querySelector('.chat-message-text:last-child .chat-image-gallery').children.length===10`, 'Sending ten images creates one message with one caption and clears the draft')
  await click('.chat-message-text:last-child .chat-image-attachment:last-child')
  await check(`document.querySelector('#chat-image-dialog').open && document.querySelector('#chat-image-full').alt==='extra-5.png'`, 'Every image in the sent gallery opens independently in the view-only viewer')
  await check(`document.querySelectorAll('#chat-image-sequence button').length===10 && document.querySelector('#chat-image-sequence [aria-current=true]').getAttribute('aria-label').includes('10 of 10') && !document.querySelector('#chat-image-previous').hidden && document.querySelector('#chat-image-next').disabled && [...document.querySelectorAll('.chat-image-nav')].every(button=>!button.textContent.trim() && button.title===button.getAttribute('aria-label'))`, 'Viewer opens the clicked image within its message sequence with icon-only arrows and a highlighted thumbnail')
  await click('#chat-image-previous')
  await check(`document.querySelector('#chat-image-full').alt==='extra-4.png' && document.querySelector('#chat-image-dialog').open && !document.querySelector('#chat-image-next').disabled`, 'Clicking the previous arrow changes the image without closing the viewer')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Left'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Left'});await pause(80)
  await check(`document.querySelector('#chat-image-full').alt==='extra-3.png'`, 'Left keyboard arrow browses the previous image')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Right'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Right'});await pause(80)
  await check(`document.querySelector('#chat-image-full').alt==='extra-4.png'`, 'Right keyboard arrow browses the next image')
  await click('#chat-image-next')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Right'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Right'});await pause(80)
  await check(`document.querySelector('#chat-image-full').alt==='extra-5.png' && document.querySelector('#chat-image-next').disabled`, 'The final image cannot navigate into a different message')
  await click('#chat-image-sequence button:first-child')
  await run(`document.querySelector('#chat-image-sequence button:first-child').focus()`)
  await check(`document.querySelector('#chat-image-full').alt==='one.png' && document.querySelector('#chat-image-previous').disabled && !document.querySelector('#chat-image-next').disabled && document.querySelector('#chat-image-position').textContent==='Image 1 of 10: one.png'`, 'Clicking a thumbnail selects that image and updates its position')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Left'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Left'});await pause(80)
  await check(`document.querySelector('#chat-image-full').alt==='one.png'`, 'The first image stays within the current message when pressing left')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Right'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Right'});await pause(80)
  await check(`document.querySelector('#chat-image-full').alt==='three.png' && document.activeElement===document.querySelector('#chat-image-sequence [aria-current=true]')`, 'Arrow navigation from the thumbnail strip keeps focus on the selected image')
  await check(`(()=>{const image=document.querySelector('#chat-image-full').getBoundingClientRect(),strip=document.querySelector('#chat-image-sequence').getBoundingClientRect();return Math.abs(strip.left+strip.width/2-innerWidth/2)<1 && strip.bottom<=innerHeight-19 && strip.top>image.bottom && [...document.querySelectorAll('.chat-image-nav')].every(button=>{const rect=button.getBoundingClientRect();return button.contains(document.elementFromPoint(rect.left+rect.width/2,rect.top+rect.height/2))})})()`, 'Thumbnail sequence sits at the bottom center without covering the image and arrow buttons are clickable')
  await shot('10-image-sequence')
  win.setSize(640,480);await pause(120)
  await click('#chat-image-sequence button:last-child')
  await check(`(()=>{const strip=document.querySelector('#chat-image-sequence').getBoundingClientRect(),current=document.querySelector('#chat-image-sequence [aria-current=true]').getBoundingClientRect(),image=document.querySelector('#chat-image-full').getBoundingClientRect();return strip.width<=innerWidth-79 && current.left>=strip.left && current.right<=strip.right && strip.top>image.bottom && document.querySelector('#chat-image-dialog').open})()`, 'Compact windows scroll the selected thumbnail into view and keep the strip below the image')
  await shot('11-image-sequence-compact')
  win.setSize(920,640);await pause(120)
  await run(`window.sequenceUrls=[...document.querySelectorAll('#chat-image-sequence img')].map(image=>image.src)`)

  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(80)
  await check(`document.querySelector('#chat-image-sequence').hidden && document.querySelector('#chat-image-sequence').children.length===0 && !document.querySelector('#chat-image-full').hasAttribute('src')`, 'Closing the multi-image viewer clears its thumbnails and displayed image')
  await check(`(async()=>{const results=await Promise.all(window.sequenceUrls.map(url=>fetch(url).then(()=>false,()=>true)));return results.every(Boolean)})()`, 'Closing the viewer releases every thumbnail object URL')
  await click('.chat-image-attachment:first-child')
  await check(`document.querySelector('#chat-image-sequence').hidden && document.querySelector('#chat-image-previous').hidden && document.querySelector('#chat-image-next').hidden`, 'Opening another single-image message clears the previous multi-image sequence')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await pause(80)
  const imageBytes=await runAsync(`return Array.from(new Uint8Array(await (await window.testImage()).arrayBuffer()))`)
  await win.webContents.session.protocol.handle('https', request => request.url.includes('/broken.png') ? new Response('',{status:404}) : new Response(new Uint8Array(imageBytes),{headers:{'content-type':'image/png'}}))
  await run(`window.uiTest.emitChat({text:'Image link: https://images.example.test/photo.png?size=large'}); window.uiTest.emitChat({text:'Broken image: https://images.example.test/broken.png'})`); await pause(300)
  await check(`document.querySelector('.chat-image-link img').naturalWidth===360 && document.querySelectorAll('.chat-image-link').length===1 && [...document.querySelectorAll('.chat-message-text a')].some(a=>a.textContent==='https://images.example.test/photo.png?size=large') && [...document.querySelectorAll('.chat-message-text a')].some(a=>a.textContent.endsWith('/broken.png'))`, 'Image URLs render previews alongside hyperlinks and broken images keep a usable hyperlink')
  await rightClick('.chat-image-link img')
  await check(`!document.querySelector('#chat-image-menu')`, 'Linked image previews expose no image action menu')
  await click('.chat-image-link')
  await check(`document.querySelector('#chat-image-dialog').open && document.querySelector('#chat-image-full').src==='https://images.example.test/photo.png?size=large'`, 'Linked image previews expand in the view-only modal')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'}); win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'}); await pause(80)
  // The intentionally broken preview emits a Chromium network error.
  for(let i=errors.length-1;i>=0;i--) if(errors[i].includes('404') || errors[i].includes('ERR_FILE_NOT_FOUND')) errors.splice(i,1)
  await shot('06-image-chat')
  await click('#leave'); await click('.room[title="the-lounge"]')
  await check(`document.querySelector('.chat-image-attachment img').naturalWidth===360`, 'Attached images survive leaving and rejoining in memory')
  await runAsync(`const original=await window.testImage();const blob=new Blob([original,new Uint8Array(10*1024*1024-original.size)],{type:'image/png'});for(let i=0;i<11;i++)window.uiTest.emitChat({text:'Memory limit '+i,images:[{name:'large.png',mimeType:'image/png',size:blob.size,blob}]})`); await pause(180)
  await check(`document.querySelectorAll('.chat-image-attachment').length===10 && document.querySelector('#chat-messages').textContent.includes('[Image removed from memory]') && document.querySelector('#chat-messages').textContent.includes('Memory limit 0')`, 'Image history evicts older attachments at 100 MB while preserving their messages')
  await run(`window.uiTest.hooks.onConnection('reconnecting')`)
  await check(`!document.querySelector('.chat-image-attachment') && document.querySelector('#chat-attachment').hidden && document.querySelector('#chat-attach').disabled`, 'Connection loss clears images and disables image attachment')
  if (errors.length) throw Error(errors.join('\n'))
  console.log('All chat UI checks passed. Screenshots: ' + output)
  clearTimeout(timeout); win.destroy(); app.exit(0)
}).catch(error => { console.error(error); clearTimeout(timeout); win?.destroy(); app.exit(1) })
