const { app, BrowserWindow } = require('./silent-electron.cjs')
const { build } = require('./build-renderer.cjs')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname, '..')
const temp = require('node:fs').mkdtempSync(path.join(os.tmpdir(), 'zodiak-linux-ui-'))
app.setPath('userData', path.join(temp, 'profile'))
app.setPath('sessionData', path.join(temp, 'session'))
process.env.ZODIAK_TEST_PLATFORM = 'linux'
app.on('window-all-closed', () => {})
let win
const timeout = setTimeout(() => { console.error('Linux UI timed out'); app.exit(1) }, 30000)
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
const run = code => win.webContents.executeJavaScript(code, true)

async function main() {
  await build({ entryPoints: [path.join(root, 'src/renderer/src/main.ts')], bundle: true, format: 'esm', outfile: path.join(temp, 'main.js'), plugins: [{ name: 'test-session', setup(build) { build.onResolve({ filter: /^\.\/session$/ }, () => ({ path: path.join(root, 'tests/ui-session.ts') })) } }] })
  const html = (await fs.readFile(path.join(root, 'src/renderer/index.html'), 'utf8')).replace('/src/styles.css', './styles.css').replace('/src/main.ts', './main.js').replaceAll('src="/logo.svg"', 'src="./logo.svg"')
  await fs.writeFile(path.join(temp, 'index.html'), html)
  await fs.copyFile(path.join(root, 'src/renderer/src/styles.css'), path.join(temp, 'styles.css'))
  await fs.copyFile(path.join(root, 'build/logo.svg'), path.join(temp, 'logo.svg'))
  await app.whenReady()
  win = new BrowserWindow({ width: 1360, height: 860, show: false, webPreferences: { preload: path.join(root, 'tests/ui-preload.cjs'), contextIsolation: true, sandbox: false, offscreen: true } })
  await win.loadFile(path.join(temp, 'index.html'))
  await pause(300)
  assert(await run(`document.querySelector('#system-audio').disabled && !document.querySelector('#system-audio').checked && document.querySelector('#block-discord-audio').disabled && !document.querySelector('#block-discord-audio').checked`))
  assert(await run(`document.querySelector('#check-for-updates').disabled && document.querySelector('#check-for-updates-on-startup').disabled && document.querySelector('#update-channel').disabled`))
  await run(`document.querySelector('.room').click()`)
  await pause(200)
  await run(`document.querySelector('#share').click()`)
  await pause(100)
  assert(await run(`document.querySelector('#picker').open && document.querySelector('#sources').hidden && document.querySelector('#refresh-sources').hidden && !document.querySelector('#go-live').disabled`))
  assert(await run(`getComputedStyle(document.querySelector('#sources')).display === 'none'`))
  await run(`document.querySelector('#go-live').click()`)
  await pause(200)
  assert(await run(`!document.querySelector('#picker').open && !document.querySelector('#stop-live').hidden`))
  await run(`document.querySelector('#stop-live').click()`)
  await pause(100)
  await run(`document.querySelector('#share').click()`)
  await pause(100)
  assert(await run(`document.querySelector('#system-audio').disabled && !document.querySelector('#go-live').disabled`))
  await fs.mkdir(path.join(root, 'release/ui-review'), { recursive: true })
  await fs.writeFile(path.join(root, 'release/ui-review/linux-share-picker.png'), (await win.webContents.capturePage()).toPNG())
  win.setSize(920, 640)
  await pause(100)
  assert(await run(`(() => { const r = document.querySelector('#picker').getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight })()`))
  console.log('PASS Linux video-only controls, manual updates, portal quality dialog, share/retry and compact-window layout')
}
main().then(() => finish(0), error => { console.error(error); void finish(1) })
async function finish(code) {
  clearTimeout(timeout)
  win?.destroy()
  await fs.rm(temp, { recursive: true, force: true }).catch(() => undefined)
  app.exit(code)
}
