const { app, BrowserWindow } = require('electron')
const { build } = require('esbuild')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname, '..')
const output = path.join(root, 'release', 'ui-review')
const errors = []
let win
const run = code => win.webContents.executeJavaScript(code, true)
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
async function check(code, label) { if (!await run(code)) throw Error(label); console.log('PASS ' + label) }
async function shot(name) { await pause(150); await fs.writeFile(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()) }
async function click(selector) { await run(`document.querySelector(${JSON.stringify(selector)}).click()`); await pause(100) }
async function noOverflow() {
  await check(`document.documentElement.scrollWidth <= innerWidth`, 'No horizontal page overflow')
  await check(`Array.from(document.querySelectorAll('#stage-head button, #call-controls button')).filter(el => el.getClientRects().length).every(el => { const r=el.getBoundingClientRect(); return r.x>=0 && r.right<=innerWidth && r.bottom<=innerHeight })`, 'Visible controls fit the window')
}
app.whenReady().then(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'zodiak-ui-'))
  await fs.mkdir(output, { recursive: true })
  await build({ entryPoints: [path.join(root, 'src/renderer/src/main.ts')], bundle: true, format: 'esm', outfile: path.join(temp, 'main.js'), plugins: [{ name: 'test-session', setup(build) { build.onResolve({ filter: /^\.\/session$/ }, () => ({ path: path.join(root, 'tests/ui-session.ts') })) } }] })
  const html = (await fs.readFile(path.join(root, 'src/renderer/index.html'), 'utf8')).replace('/src/styles.css', './styles.css').replace('/src/main.ts', './main.js')
  await fs.writeFile(path.join(temp, 'index.html'), html)
  await fs.copyFile(path.join(root, 'src/renderer/src/styles.css'), path.join(temp, 'styles.css'))
  win = new BrowserWindow({ width: 1360, height: 860, show: false, frame: false, webPreferences: { preload: path.join(root, 'tests/ui-preload.cjs'), contextIsolation: true, sandbox: false, backgroundThrottling: false, offscreen: true } })
  win.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message) })
  await win.loadFile(path.join(temp, 'index.html')); await pause(400)
  await check(`document.querySelectorAll('.room').length === 3`, 'Room directory loads')
  await noOverflow(); await shot('01-lobby')
  await check(`!document.querySelector('.app-titlebar').textContent.trim() && !document.querySelector('.workspace-heading')`, 'App and room labels are removed from navigation')
  await check(`document.querySelectorAll('.workspace-rail .room').length === 3 && document.querySelectorAll('[data-settings]').length === 1`, 'Room rail and settings are not duplicated')
  await check(`getComputedStyle(document.querySelector('.app-titlebar')).borderBottomWidth==='1px'`, 'Title bar has a visual divider')
  await click('#server-settings')
  await check(`document.querySelector('#server-dialog').open && document.querySelector('#server-url') && document.querySelector('#api-key') && document.querySelector('#api-secret') && !document.querySelector('#server-details')`, 'Server connection is available directly from the room rail')
  await click('[data-close="server-dialog"]')
  await run(`window.sharescreen.setTestServerAvailable(false)`)
  await click('#server-settings'); await click('#save-server-settings')
  await check(`document.querySelector('#create-room-action').hidden && !document.querySelector('#room-list').textContent.trim() && !document.querySelector('#waiting-message').hidden`, 'Unavailable servers show an empty rail and a connection error')
  await run(`window.sharescreen.setTestServerAvailable(true)`)
  await click('#server-settings'); await click('#save-server-settings')
  await check(`!document.querySelector('#create-room-action').hidden && document.querySelectorAll('.room').length === 3`, 'Room creation returns when the server is reachable')
  await click('.room-delete')
  await check(`document.querySelector('#delete-dialog').open`, 'Room deletion uses an in-app confirmation dialog')
  await click('[data-close="delete-dialog"]')
  await click('.room')
  await check(`document.querySelectorAll('.participant-tile').length===3 && !document.querySelector('#participant-grid').hidden`, 'Joining shows participant tiles')
  await check(`!document.querySelector('#room-sidebar').hidden && document.querySelectorAll('#members-list .member').length===3`, 'Room sidebar shows connected people')
  await check(`Array.from(document.querySelectorAll('#call-controls button')).every(el => !el.textContent.trim() && el.getAttribute('aria-label') && el.title)`, 'Call controls are icons with accessible names and tooltips')
  await noOverflow(); await shot('02-room')
  win.setSize(920, 640); await pause(120); await noOverflow(); await shot('03-room-small')
  await click('#share')
  await check(`document.querySelector('#picker').open && document.querySelectorAll('.source').length===2`, 'Share picker opens and loads sources')
  await check(`document.querySelector('#go-live').disabled`, 'Share requires an explicit source selection')
  await check(`document.querySelector('#share-resolution').value==='1080p' && document.querySelector('#share-framerate').value==='60' && document.querySelector('#system-audio').checked && document.querySelector('#block-discord-audio').checked`, 'Share defaults use protected system audio and optional Discord exclusion')
  await check(`!document.querySelector('#picker-title') && !document.querySelector('#settings-title')`, 'Settings and share dialogs have no redundant titles')
  await shot('04-picker-small')
  await run(`document.querySelector('#share-resolution').value='4k'; document.querySelector('#share-resolution').dispatchEvent(new Event('change'))`)
  await check(`document.querySelector('#share-framerate').value==='24' && document.querySelector('#share-framerate option[value="60"]').disabled`, '4K limits frame rate')
  await check(`document.querySelector('#block-discord-audio').checked && !document.querySelector('#block-discord-audio').disabled`, 'Discord exclusion remains optional')
  await click('.source'); await click('#go-live')
  await check(`!document.querySelector('#picker').open && !document.querySelector('#stop-live').hidden`, 'Go live closes picker and exposes stop control')
  await run(`window.uiTest.emitStreams([{id:'local',participantId:'me',participantName:'Alex Morgan',local:true,muted:false},{id:'remote',participantId:'sam',participantName:'Sam Rivera',local:false,muted:false},{id:'remote2',participantId:'jo',participantName:'Jordan Lee',local:false,muted:false}])`)
  await check(`window.uiTest.targets.length===3 && document.querySelectorAll('#stream-grid .grid-tile').length===3 && !document.querySelector('#stream-grid').hidden && !document.querySelector('#streams-panel')`, 'Streams and people use one central grid without a stream list')
  await run(`const slider=document.querySelector('.grid-tile-volume'); slider.value='42'; slider.dispatchEvent(new Event('input', { bubbles: true }))`)
  await check(`window.uiTest.streamVolume===.42`, 'Each remote stream has an independent volume control')
  await noOverflow(); await shot('05-streams-small')
  await click('#hide-my-screen')
  await check(`!window.uiTest.targets.includes('local') && window.uiTest.targets.length===2`, 'Hide local preview removes it from grid')
  await click('.grid-tile.is-stream')
  await check(`document.querySelector('#stream-grid').hidden && window.uiTest.selected`, 'Selecting a stream focuses it')
  await check(`!document.querySelector('#focused-stream-volume').hidden`, 'Focused remote stream keeps its independent volume control')
  await run(`const focusedSlider=document.querySelector('#focused-stream-volume-input'); focusedSlider.value='64'; focusedSlider.dispatchEvent(new Event('input', { bubbles: true }))`)
  await check(`window.uiTest.streamVolume===.64 && document.querySelector('#focused-stream-volume-value').textContent==='64%'`, 'Focused stream volume updates independently')
  await click('#fullscreen')
  await check(`document.body.classList.contains('theater') && document.querySelector('#fullscreen').title==='Exit fullscreen'`, 'Fullscreen uses the native window and focuses the stream')
  await click('#exit-focus')
  await check(`!document.body.classList.contains('theater') && document.querySelector('#fullscreen').title==='Fullscreen'`, 'Exiting focus leaves native fullscreen')
  await click('#stage-video')
  await check(`!document.querySelector('#stream-grid').hidden`, 'Clicking the focused stream returns to the grid')
  await click(".grid-tile[aria-label=\"Focus Sam Rivera's screen\"]")
  await click('#theater')
  await check(`document.body.classList.contains('theater') && !document.querySelector('#exit-focus').hidden && getComputedStyle(document.querySelector('.workspace-rail')).display==='none' && getComputedStyle(document.querySelector('#shell')).gridTemplateColumns.split(' ').length===1`, 'Focus view fills the screen and has a visible exit')
  await check(`!document.querySelector('#focused-stream-volume').hidden`, 'Focus view shows the selected stream volume control')
  await click('#exit-focus')
  await click('[data-settings]')
  await check(`!document.querySelector('#server-details')`, 'General settings no longer contain server credentials')
  await run(`document.querySelector('#audio-volume').value='37'; document.querySelector('#audio-volume').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.volume===.37 && document.querySelector('#audio-volume-value').textContent==='37%'`, 'Audio volume updates session')
  await shot('06-settings-small')
  await run(`document.querySelector('#display-name').value='Unsaved name'`)
  await click('[data-close="settings-dialog"]')
  await check(`document.querySelector('#display-name').value==='Alex Morgan'`, 'Closing settings discards unsaved profile changes')
  await click('#leave')
  await check(`!document.querySelector('#waiting').hidden && document.querySelector('#call-controls').hidden`, 'Leaving restores lobby')
  await click('[data-create-room]')
  await run(`document.querySelector('#new-room').value='new-room'; document.querySelector('#create-form').requestSubmit()`); await pause(180)
  await check(`!document.querySelector('#create-dialog').open && document.querySelector('#room-title').textContent==='new-room'`, 'Create room joins the new room')
  if (errors.length) throw Error(errors.join('\n'))
  console.log('All UI smoke checks passed. Screenshots: ' + output)
  win.destroy(); app.exit(0)
}).catch(error => { console.error(error); win?.destroy(); app.exit(1) })
