const { app, BrowserWindow } = require('electron')
const { build } = require('esbuild')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname, '..')
const output = path.join(root, 'release', 'ui-review')
const errors = []
let win
const run = code => win.webContents.executeJavaScript(code, true)
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
async function check(code, label) { if (!await run(code)) throw Error(label); console.log('PASS ' + label) }
async function shot(name) { await pause(150); await fs.writeFile(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()) }
async function click(selector) { await run(`document.querySelector(${JSON.stringify(selector)}).click()`); await pause(100) }
async function noOverflow() {
  await check(`document.documentElement.scrollWidth <= innerWidth`, 'No horizontal page overflow')
  await check(`Array.from(document.querySelectorAll('#stage-head button, #call-controls button')).filter(el => el.getClientRects().length).every(el => { const r=el.getBoundingClientRect(); return r.x>=0 && r.right<=innerWidth && r.bottom<=innerHeight })`, 'Visible controls fit the window')
}
app.whenReady().then(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'zodiak-ui-'))
  await fs.mkdir(output, { recursive: true })
  await build({ entryPoints: [path.join(root, 'src/renderer/src/main.ts')], bundle: true, format: 'esm', outfile: path.join(temp, 'main.js'), plugins: [{ name: 'test-session', setup(build) { build.onResolve({ filter: /^\.\/session$/ }, () => ({ path: path.join(root, 'tests/ui-session.ts') })) } }] })
  const html = (await fs.readFile(path.join(root, 'src/renderer/index.html'), 'utf8')).replace('/src/styles.css', './styles.css').replace('/src/main.ts', './main.js').replace('src="/logo.svg"', 'src="./logo.svg"')
  await fs.writeFile(path.join(temp, 'index.html'), html)
  await fs.copyFile(path.join(root, 'src/renderer/src/styles.css'), path.join(temp, 'styles.css'))
  await fs.copyFile(path.join(root, 'build/logo.svg'), path.join(temp, 'logo.svg'))
  win = new BrowserWindow({ width: 1360, height: 860, show: false, frame: false, webPreferences: { preload: path.join(root, 'tests/ui-preload.cjs'), contextIsolation: true, sandbox: false, backgroundThrottling: false, offscreen: true } })
  win.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message) })
  await win.loadFile(path.join(temp, 'index.html')); await pause(400)
  await check(`document.querySelectorAll('.room').length === 3`, 'Room directory loads')
  await noOverflow(); await shot('01-lobby')
  await check(`!document.querySelector('.app-titlebar-label') && !document.querySelector('.workspace-heading')`, 'Title bar contains only the app logo')
  await check(`(() => { const logo = document.querySelector('.app-titlebar-logo'); const bounds = logo?.getBoundingClientRect(); return logo?.complete && logo.naturalWidth > 0 && bounds.width === 22 && Math.abs((bounds.left + bounds.right) / 2 - innerWidth / 2) < 1 })()`, 'Title-bar logo is horizontally centered')
  await check(`(() => { const settings = document.querySelector('#lobby-settings'); const server = document.querySelector('#server-settings'); const rail = document.querySelector('.workspace-rail'); return document.querySelectorAll('.workspace-rail .room').length === 3 && document.querySelectorAll('[data-settings]').length === 1 && getComputedStyle(settings).display !== 'none' && settings.nextElementSibling === server && settings.getBoundingClientRect().bottom < server.getBoundingClientRect().top && rail.getBoundingClientRect().bottom - server.getBoundingClientRect().bottom < 20 })()`, 'Lobby settings sits above the fixed server shortcut')
  await check(`getComputedStyle(document.querySelector('.app-titlebar')).borderBottomWidth==='1px'`, 'Title bar has a visual divider')
  await click('#server-settings')
  await check(`document.querySelector('#server-dialog').open && document.querySelector('#server-url') && document.querySelector('#api-key') && document.querySelector('#api-secret') && !document.querySelector('#server-details')`, 'Server connection is available directly from the room rail')
  await click('[data-close="server-dialog"]')
  await run(`window.sharescreen.setTestServerAvailable(false)`)
  await click('#server-settings'); await click('#save-server-settings')
  await check(`document.querySelector('#create-room-action').hidden && !document.querySelector('#room-list').textContent.trim() && !document.querySelector('#waiting-message').hidden`, 'Unavailable servers show an empty rail and a connection error')
  await run(`window.sharescreen.setTestServerAvailable(true)`)
  await click('#server-settings'); await click('#save-server-settings')
  await check(`!document.querySelector('#create-room-action').hidden && document.querySelectorAll('.room').length === 3`, 'Room creation returns when the server is reachable')
  await click('.room-delete')
  await check(`document.querySelector('#delete-dialog').open`, 'Room deletion uses an in-app confirmation dialog')
  await click('[data-close="delete-dialog"]')
  await click('.room')
  await check(`document.querySelectorAll('.participant-tile').length===3 && !document.querySelector('#participant-grid').hidden`, 'Joining shows participant tiles')
  await check(`getComputedStyle(document.querySelector('#lobby-settings')).display === 'none'`, 'Lobby settings shortcut hides in a room')
  await check(`!document.querySelector('#room-sidebar').hidden && document.querySelectorAll('#members-list .member').length===3`, 'Room sidebar shows connected people')
  await check(`(() => { const icon = document.querySelector('.members-heading [data-icon="people"]'); const count = document.querySelector('#members-count'); const iconBounds = icon.getBoundingClientRect(); const countBounds = count.getBoundingClientRect(); return count.textContent==='3' && countBounds.left >= iconBounds.right && countBounds.left - iconBounds.right <= 7 && getComputedStyle(count).fontSize==='12px' })()`, 'Participant count sits beside the icon at a readable size')
  await check(`Array.from(document.querySelectorAll('#members-list .member-name')).map(el => el.textContent).join(',')==='Alex Morgan,Jordan Lee,Sam Rivera'`, 'Member list is alphabetical')
  await run(`window.uiTest.emitStreams([{id:'remote',participantId:'sam',participantName:'Sam Rivera',local:false,muted:false,subscribed:false},{id:'remote2',participantId:'jo',participantName:'Jordan Lee',local:false,muted:false,subscribed:false}])`)
  await check(`!document.querySelector('#stream-grid').hidden && document.querySelector('#grid-view').hidden && document.querySelectorAll('#stream-grid .is-available').length===2`, 'Unwatched streams keep the overview open without a focus action')
  await run(`window.uiTest.emitStreams([])`)
  await run(`window.memberNodes = [...document.querySelectorAll('#members-list .member')]; window.participantNodes = [...document.querySelectorAll('.participant-tile')]; window.uiTest.emitParticipants([{ id: 'sam', name: 'Sam Rivera', local: false }, { id: 'jo', name: 'Jordan Lee', local: false }, { id: 'me', name: 'Alex Morgan', local: true }])`)
  await check(`window.memberNodes.every((node, index) => node === document.querySelectorAll('#members-list .member')[index]) && window.participantNodes.every((node, index) => node === document.querySelectorAll('.participant-tile')[index])`, 'Reordered roster refresh preserves member order and existing tiles')
  await run(`window.uiTest.emitParticipants([{ id: 'me', name: 'Alex Morgan', local: true }, { id: 'sam', name: 'Sam Rivera', local: false }, { id: 'jo', name: 'Jordan Lee', local: false }, { id: 'lina', name: 'Lina Park', local: false }])`)
  await check(`document.querySelectorAll('#members-list .member').length===4 && document.querySelector('#members-list').textContent.includes('Lina Park')`, 'Member list updates when someone joins')
  await run(`window.uiTest.emitParticipants([{ id: 'me', name: 'Alex Morgan', local: true }, { id: 'sam', name: 'Sam Rivera', local: false }, { id: 'jo', name: 'Jordan Lee', local: false }])`)
  await check(`document.querySelectorAll('#members-list .member').length===3 && !document.querySelector('#members-list').textContent.includes('Lina Park')`, 'Member list updates when someone leaves')
  await check(`!document.querySelector('#toggle-stats')`, 'Statistics control is not in the stage header')
  await check(`Array.from(document.querySelectorAll('#call-controls button')).every(el => !el.textContent.trim() && el.getAttribute('aria-label') && el.title)`, 'Call controls are icons with accessible names and tooltips')
  await noOverflow(); await shot('02-room')
  win.setSize(920, 640); await pause(120); await noOverflow(); await shot('03-room-small')
  await click('#share')
  await check(`document.querySelector('#picker').open && document.querySelectorAll('.source').length===2`, 'Share picker opens and loads sources')
  await check(`document.querySelector('#go-live').disabled`, 'Share requires an explicit source selection')
  await check(`document.querySelector('#share-resolution').value==='1080p' && document.querySelector('#share-framerate').value==='60' && document.querySelector('#share-priority').value==='framerate' && document.querySelector('#share-bitrate-mode').value==='dynamic' && document.querySelector('#system-audio').checked && document.querySelector('#block-discord-audio').checked`, 'Share defaults prioritize frame rate with adaptive bitrate and protected system audio')
  await check(`document.querySelector('#share-framerate option[value="120"]').disabled`, '120 FPS is limited to 480p and 720p')
  await run(`document.querySelector('#share-resolution').value='720p'; document.querySelector('#share-resolution').dispatchEvent(new Event('change')); document.querySelector('#share-framerate').value='120'; document.querySelector('#share-framerate').dispatchEvent(new Event('change'))`)
  await check(`document.querySelector('#share-framerate').value==='120' && document.querySelector('#share-bitrate').min==='6000000' && document.querySelector('#share-bitrate').max==='16000000' && document.querySelector('#share-bitrate-mode').title.includes('6.0 Mb/s–16.0 Mb/s')`, '720p at 120 FPS uses a 6–16 Mb/s adaptive bitrate range')
  await run(`document.querySelector('#share-resolution').value='480p'; document.querySelector('#share-resolution').dispatchEvent(new Event('change'))`)
  await check(`document.querySelector('#share-framerate').value==='120' && document.querySelector('#share-bitrate').min==='3500000' && document.querySelector('#share-bitrate').max==='9000000' && document.querySelector('#share-bitrate-mode').title.includes('3.5 Mb/s–9.0 Mb/s')`, '480p at 120 FPS uses a 3.5–9 Mb/s adaptive bitrate range')
  await check(`!document.querySelector('#capture-acceleration')`, 'Share picker keeps diagnostics inside the statistics panel')
  await run(`document.querySelector('#share-resolution').value='1440p'; document.querySelector('#share-resolution').dispatchEvent(new Event('change')); document.querySelector('#share-framerate').value='60'; document.querySelector('#share-framerate').dispatchEvent(new Event('change')); document.querySelector('#share-bitrate-mode').value='fixed'; document.querySelector('#share-bitrate-mode').dispatchEvent(new Event('change')); document.querySelector('#share-bitrate').value='12300000'; document.querySelector('#share-bitrate').dispatchEvent(new Event('input'))`)
  await check(`document.querySelector('#share-framerate').value==='60' && document.querySelector('#share-framerate option[value="60"]').disabled===false && !document.querySelector('#fixed-bitrate-field').hidden && document.querySelector('#share-bitrate').min==='5000000' && document.querySelector('#share-bitrate').max==='20000000' && document.querySelector('#share-bitrate-value').textContent==='12.3 Mb/s'`, '1440p supports 60 FPS with a bounded fixed bitrate slider')
  await check(`!document.querySelector('#picker-title') && !document.querySelector('#settings-title')`, 'Settings and share dialogs have no redundant titles')
  await shot('04-picker-small')
  await check(`!document.querySelector('#share-resolution option[value="4k"]')`, '4K is not offered as a share resolution')
  await check(`document.querySelector('#block-discord-audio').checked && !document.querySelector('#block-discord-audio').disabled`, 'Discord exclusion remains optional')
  await click('.source'); await click('#go-live')
  await check(`!document.querySelector('#picker').open && !document.querySelector('#stop-live').hidden && window.uiTest.quality.bitrate===12300000 && window.uiTest.quality.priority==='framerate'`, 'Go live applies the selected priority and fixed bitrate')
  await run(`window.uiTest.emitStreams([{id:'local',participantId:'me',participantName:'Alex Morgan',local:true,muted:false,subscribed:true},{id:'remote',participantId:'sam',participantName:'Sam Rivera',local:false,muted:false,subscribed:false},{id:'remote2',participantId:'jo',participantName:'Jordan Lee',local:false,muted:false,subscribed:false}])`)
  await check(`window.uiTest.targets.length===1 && document.querySelectorAll('#stream-grid .is-available').length===2`, 'Joining lists remote screens without rendering them')
  await check(`document.querySelectorAll('#stream-grid .stream-available-monitor').length===2 && Array.from(document.querySelectorAll('#stream-grid .stream-available-status')).every(el => el.textContent==='Sharing screen')`, 'Available screen cards clearly identify active sharing')
  await check(`(() => { const tile = document.querySelector('#stream-grid .is-available'); const monitor = tile.querySelector('.stream-available-monitor'); const icon = monitor.querySelector('.icon'); return getComputedStyle(tile).backgroundImage==='none' && getComputedStyle(tile).backgroundColor==='rgb(32, 35, 49)' && getComputedStyle(monitor).borderTopWidth==='0px' && getComputedStyle(monitor).backgroundColor==='rgba(0, 0, 0, 0)' && parseFloat(getComputedStyle(icon).width)>=46 })()`, 'Available screen cards use a distinct solid sharing surface and prominent unframed monitor')
  await check(`document.querySelectorAll('#stream-grid .start-watching').length===2 && document.querySelector('#stream-grid .start-watching-label').textContent==='Click to watch'`, 'Available screen cards show a Click to watch control')
  await click(`[aria-label="Click to watch Sam Rivera's screen"]`)
  await check(`window.uiTest.targets.includes('remote')`, 'Clicking an available screen starts only that stream')
  await click('.grid-tile-hide')
  await check(`!window.uiTest.targets.includes('remote') && document.querySelectorAll('.grid-tile.is-available').length===2`, 'Hiding a stream stops rendering and returns it to an available card')
  await run(`window.uiTest.emitStreams([{id:'local',participantId:'me',participantName:'Alex Morgan',local:true,muted:false,subscribed:true},{id:'remote',participantId:'sam',participantName:'Sam Rivera',local:false,muted:false,subscribed:true},{id:'remote2',participantId:'jo',participantName:'Jordan Lee',local:false,muted:false,subscribed:true}])`)
  await check(`window.uiTest.targets.length===3 && document.querySelectorAll('#stream-grid .grid-tile').length===3 && !document.querySelector('#stream-grid').hidden && !document.querySelector('#streams-panel')`, 'Streams and people use one central grid without a stream list')
  await check(`Array.from(document.querySelectorAll('#members-list .member-live')).map(el => el.textContent).join(',')==='LIVE,LIVE,LIVE' && Array.from(document.querySelectorAll('#members-list .member-live')).every(el => getComputedStyle(el).borderRadius==='0px' && getComputedStyle(el).backgroundColor==='rgba(0, 0, 0, 0)')`, 'Streaming participants have compact outlined LIVE badges')
  await run(`window.uiTest.emitParticipants([{ id: 'me', name: 'Alex Morgan', local: true }, { id: 'sam', name: 'Sam Rivera', local: false }, { id: 'jo', name: 'Jordan Lee', local: false }, { id: 'lina', name: 'Lina Park', local: false }])`)
  await check(`Array.from(document.querySelectorAll('#members-list .member-name')).map(el => el.textContent).join(',')==='Alex Morgan,Jordan Lee,Sam Rivera,Lina Park'`, 'Participant list puts LIVE members first and alphabetizes each group')
  await check(`Array.from(document.querySelectorAll('#stream-grid .grid-tile-label')).map(el => el.textContent).join(',')==='Alex Morgan,Jordan Lee,Sam Rivera,Lina Park'`, 'Grid lists screen sharers before non-streaming participants')
  await run(`window.uiTest.emitStreams([{id:'local',participantId:'me',participantName:'Zoe',local:true,muted:false,subscribed:true},{id:'remote',participantId:'sam',participantName:'Alpha',local:false,muted:false,subscribed:true},{id:'remote2',participantId:'jo',participantName:'Aaron',local:false,muted:false,subscribed:false}]); window.uiTest.emitParticipants([{ id: 'me', name: 'Zoe', local: true }, { id: 'sam', name: 'Alpha', local: false }, { id: 'jo', name: 'Aaron', local: false }, { id: 'lina', name: 'Bea', local: false }])`)
  await check(`Array.from(document.querySelectorAll('#stream-grid .grid-tile-label')).map(el => el.textContent).join(',')==='Alpha,Zoe,Aaron,Bea'`, 'Grid orders watched, then unwatched streams, then non-streaming people alphabetically')
  await run(`window.uiTest.emitStreams([{id:'local',participantId:'me',participantName:'Alex Morgan',local:true,muted:false,subscribed:true},{id:'remote',participantId:'sam',participantName:'Sam Rivera',local:false,muted:false,subscribed:true},{id:'remote2',participantId:'jo',participantName:'Jordan Lee',local:false,muted:false,subscribed:true}])`)
  await run(`window.uiTest.emitParticipants([{ id: 'me', name: 'Alex Morgan', local: true }, { id: 'sam', name: 'Sam Rivera', local: false }, { id: 'jo', name: 'Jordan Lee', local: false }])`)
  await check(`Array.from(document.querySelectorAll('.grid-stream-audio-controls')).every(control => parseFloat(getComputedStyle(control).height)<60 && Number(getComputedStyle(control.querySelector('.grid-tile-volume')).opacity)===0)`, 'Grid stream controls retract to mute buttons')
  await check(`Array.from(document.querySelectorAll('.grid-stream-hide-control')).every(control => Number(getComputedStyle(control).opacity)===.72 && getComputedStyle(control).width===getComputedStyle(document.querySelector('.grid-stream-audio-controls')).width && getComputedStyle(control).backgroundColor===getComputedStyle(document.querySelector('.grid-stream-audio-controls')).backgroundColor && getComputedStyle(control).borderRadius===getComputedStyle(document.querySelector('.grid-stream-audio-controls')).borderRadius)`, 'Grid Hide controls use a fixed outer shell matching the audio controls')
  await check(`document.querySelector('.grid-tile-volume').max==='100' && document.querySelector('#audio-volume').max==='200' && document.querySelector('#focused-stream-volume-input').max==='100'`, 'Only the global volume control supports up to 200%')
  await run(`const globalSlider=document.querySelector('#audio-volume'); globalSlider.value='200'; globalSlider.dispatchEvent(new Event('input', { bubbles: true }))`)
  await check(`window.uiTest.volume===2`, 'Global volume boost reaches 200%')
  await run(`const lowerSlider=document.querySelector('.grid-tile-volume'); lowerSlider.value='42'; lowerSlider.dispatchEvent(new Event('input', { bubbles: true }))`)
  await check(`window.uiTest.streamVolume===.42`, 'Each remote stream has an independent volume control')
  await click('.grid-tile-mute')
  await run(`const mutedSlider=document.querySelector('.grid-tile-volume'); mutedSlider.value='43'; mutedSlider.dispatchEvent(new Event('input', { bubbles: true }))`)
  await check(`document.querySelector('.grid-tile-mute').getAttribute('aria-pressed')==='false'`, 'Adjusting a muted stream volume immediately unmutes it')
  await noOverflow(); await shot('05-streams-small')
  await click('#hide-my-screen')
  await check(`!window.uiTest.targets.includes('local') && window.uiTest.targets.length===2 && Array.from(document.querySelectorAll('.grid-tile.is-available .grid-tile-label')).some(el => el.textContent==='Alex Morgan')`, 'Hide local preview turns the local share into an available card')
  await click(`[aria-label="Click to watch Alex Morgan's screen"]`)
  await check(`window.uiTest.selected==='local' && window.uiTest.targets.includes('local') && !document.querySelector('#stream-grid').hidden && document.querySelector('#hide-my-screen').getAttribute('aria-pressed')==='false'`, 'Clicking the hidden local share restores its preview')
  await click('#stage-video')
  await click('#hide-my-screen')
  await click(".grid-tile[aria-label=\"Focus Sam Rivera's screen\"]")
  await check(`document.querySelector('#stream-grid').hidden && window.uiTest.selected`, 'Selecting a stream focuses it')
  await check(`document.querySelector('#hide-my-screen').getAttribute('aria-pressed')==='true' && document.querySelector('#hide-my-screen').title==='Show my screen'`, 'Hidden local preview remains hidden in focus view')
  await check(`getComputedStyle(document.querySelector('#stream-metrics')).left==='26px' && getComputedStyle(document.querySelector('#stream-metrics')).right==='auto'`, 'Focused-stream statistics avoid the volume control')
  await click('[data-settings]')
  await check(`document.querySelector('#show-stream-statistics') && !document.querySelector('#show-stream-statistics').checked`, 'Statistics visibility is configured in settings')
  await run(`const option=document.querySelector('#show-stream-statistics'); option.checked=true; option.dispatchEvent(new Event('change', { bubbles: true }))`)
  await click('#save-settings')
  await run(`window.uiTest.emitTelemetry({ sent: { bytes: 216000000, bitrate: 8200000, targetBitrate: 12000000, maxBitrate: 12000000, qualityLimitationReason: 'cpu', qualityLimitationDurationMs: 1800, captureWidth: 2560, captureHeight: 1440, captureFrameRate: 60, packetRate: 900, packets: 12500, packetsLost: 2, packetLossPercent: .04, frameRate: 59.8, width: 1920, height: 1080, roundTripTimeMs: 18, jitterMs: 2 }, received: { bytes: 195000000, bitrate: 7600000, packetRate: 860, packets: 12100, packetsLost: 4, packetLossPercent: .08, frameRate: 59.1, width: 1920, height: 1080, codec: 'video/H264', decoder: 'D3D11', framesDropped: 3, jitterMs: 3, jitterBufferDelayMs: 14, decodeTimeMs: 2 } })`)
  await check(`!document.querySelector('#stream-metrics').hidden && !document.querySelector('#host-metrics').hidden && !document.querySelector('#viewer-metrics').hidden && document.querySelector('#host-metrics').textContent.includes('Budget') && document.querySelector('#host-metrics').textContent.includes('GPU encode') && document.querySelector('#host-metrics').textContent.includes('CPU / encoder') && document.querySelector('#host-metrics').textContent.includes('Capture') && document.querySelector('#host-metrics').textContent.includes('12.0 Mb/s') && document.querySelector('#host-metrics').textContent.includes('Packet rate') && document.querySelector('#viewer-metrics').textContent.includes('D3D11') && document.querySelector('#viewer-metrics').textContent.includes('Decode')`, 'Statistics distinguish capture, GPU, encoder limits, and viewer decode telemetry')
  await run(`document.querySelector('#stream-metrics').dispatchEvent(new Event('pointerenter'))`)
  await pause(1800)
  await check(`!document.querySelector('#stage-wrap').classList.contains('screen-controls-idle')`, 'Hovering statistics keeps overlays visible')
  await run(`document.querySelector('#stream-metrics').dispatchEvent(new Event('pointerleave'))`)
  await check(`!document.querySelector('#focused-stream-volume').hidden`, 'Focused remote stream keeps its independent volume control')
  await run(`const focusedSlider=document.querySelector('#focused-stream-volume-input'); focusedSlider.value='64'; focusedSlider.dispatchEvent(new Event('input', { bubbles: true }))`)
  await check(`window.uiTest.streamVolume===.64 && document.querySelector('#focused-stream-volume-value').textContent==='64%'`, 'Focused stream volume updates independently')
  await check(`document.querySelector('#stream-grid').hidden`, 'Focused stream volume control does not activate the background stream')
  await click('#focused-stream-mute')
  await check(`document.querySelector('#focused-stream-mute').getAttribute('aria-pressed')==='true' && document.querySelector('#focused-stream-mute').title==='Unmute Sam Rivera'`, 'Focused stream mute button toggles audio')
  await check(`document.querySelector('#stream-grid').hidden`, 'Focused stream mute control does not activate the background stream')
  await click('#fullscreen')
  await check(`document.body.classList.contains('theater') && document.querySelector('#fullscreen').title==='Exit fullscreen'`, 'Fullscreen uses the native window and focuses the stream')
  await pause(2800)
  await check(`document.querySelector('#stage-wrap').classList.contains('screen-controls-idle') && Number(getComputedStyle(document.querySelector('#exit-focus')).opacity)<.1 && Number(getComputedStyle(document.querySelector('#focused-stream-volume')).opacity)<.1 && Number(getComputedStyle(document.querySelector('#focused-stream-hide')).opacity)<.1 && Number(getComputedStyle(document.querySelector('#stream-metrics')).opacity)<.1`, 'Floating controls hide after pointer inactivity')
  await run(`document.querySelector('#stage-wrap').dispatchEvent(new Event('pointermove', { bubbles: true }))`)
  await pause(250)
  await check(`!document.querySelector('#stage-wrap').classList.contains('screen-controls-idle') && getComputedStyle(document.querySelector('#exit-focus')).opacity==='1'`, 'Pointer movement restores floating screen controls')
  await click('#exit-focus')
  await check(`!document.body.classList.contains('theater') && document.querySelector('#fullscreen').title==='Fullscreen'`, 'Exiting focus leaves native fullscreen')
  await click('#stage-video')
  await check(`!document.querySelector('#stream-grid').hidden`, 'Clicking the focused stream returns to the grid')
  await run(`document.querySelector('#stage-wrap').dispatchEvent(new Event('pointermove', { bubbles: true }))`)
  await pause(1800)
  await check(`Array.from(document.querySelectorAll('.grid-stream-hide-control')).every(control => Number(getComputedStyle(control).opacity)<.1)`, 'Grid Hide controls follow the inactivity fade')
  await check(`document.querySelector('#stream-metrics').hidden`, 'Statistics are hidden outside focus view')
  await click(".grid-tile[aria-label=\"Focus Sam Rivera's screen\"]")
  await click('#theater')
  await check(`document.body.classList.contains('theater') && !document.querySelector('#exit-focus').hidden && getComputedStyle(document.querySelector('.workspace-rail')).display==='none' && getComputedStyle(document.querySelector('#shell')).gridTemplateColumns.split(' ').length===1`, 'Focus view fills the screen and has a visible exit')
  await check(`!document.querySelector('#focused-stream-volume').hidden`, 'Focus view shows the selected stream volume control')
  await click('#exit-focus')
  await click('[data-settings]')
  await check(`!document.querySelector('#server-details')`, 'General settings no longer contain server credentials')
  await run(`document.querySelector('#display-name').value='Renamed Alex'`)
  await click('#save-settings')
  await check(`Array.from(document.querySelectorAll('#members-list .member-name')).some(el => el.textContent==='Renamed Alex') && document.querySelector('#profile-name').textContent==='Renamed Alex'`, 'Saving a name updates the in-room member list immediately')
  await click('[data-settings]')
  await run(`document.querySelector('#audio-volume').value='37'; document.querySelector('#audio-volume').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.volume===.37 && document.querySelector('#audio-volume-value').textContent==='37%'`, 'Audio volume updates session')
  await shot('06-settings-small')
  await run(`document.querySelector('#display-name').value='Unsaved name'`)
  await click('[data-close="settings-dialog"]')
  await check(`document.querySelector('#display-name').value==='Renamed Alex'`, 'Closing settings discards unsaved profile changes')
  await click('#leave')
  await check(`!document.querySelector('#waiting').hidden && document.querySelector('#call-controls').hidden`, 'Leaving restores lobby')
  await click('[data-create-room]')
  await run(`document.querySelector('#new-room').value='new-room'; document.querySelector('#create-form').requestSubmit()`); await pause(180)
  await check(`!document.querySelector('#create-dialog').open && document.querySelector('#room-title').textContent==='new-room'`, 'Create room joins the new room')
  if (errors.length) throw Error(errors.join('\n'))
  console.log('All UI smoke checks passed. Screenshots: ' + output)
  win.destroy(); app.exit(0)
}).catch(error => { console.error(error); win?.destroy(); app.exit(1) })
