const { app, BrowserWindow, ipcMain } = require('./silent-electron.cjs')
const assert = require('node:assert/strict')
const { build } = require('esbuild')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname, '..')
const output = path.join(root, 'release/update-review')
const profile = require('node:fs').mkdtempSync(path.join(os.tmpdir(), 'zodiak-update-ui-'))
app.setPath('userData', profile)
app.setPath('sessionData', path.join(profile, 'session'))
let win
let state = { revision: 0, phase: 'idle', visible: false, channel: 'stable' }
const actions = [], errors = []
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
const run = code => win.webContents.executeJavaScript(code, true)
async function check(code, label) { assert.ok(await run(code), label); console.log('PASS ' + label) }
async function send(next) {
  state = { ...next, revision: state.revision + 1, channel: 'stable', visible: next.visible ?? true }
  win.webContents.send('update:state:changed', state)
  await pause(80)
}
async function shot(name) {
  await pause(260)
  const bounds = await run(`(() => { const r=document.querySelector('#update-dialog').getBoundingClientRect(); return {x:Math.floor(r.x)-12,y:Math.floor(r.y)-12,width:Math.ceil(r.width)+24,height:Math.ceil(r.height)+24} })()`)
  await fs.writeFile(path.join(output, name + '.png'), (await win.webContents.capturePage(bounds)).toPNG())
}

app.whenReady().then(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'zodiak-update-ui-build-'))
  await fs.mkdir(output, { recursive: true })
  await build({ stdin: { contents: "import {initializeUpdateUI} from './src/renderer/src/update-ui'; import {hydrateIcons} from './src/renderer/src/icons'; hydrateIcons(); initializeUpdateUI(window.sharescreen)", resolveDir: root, loader: 'ts' }, bundle: true, format: 'esm', outfile: path.join(temp, 'main.js') })
  await build({ entryPoints: [path.join(root, 'src/preload/index.ts')], bundle: true, platform: 'node', format: 'cjs', external: ['electron'], outfile: path.join(temp, 'preload.cjs') })
  const html = (await fs.readFile(path.join(root, 'src/renderer/index.html'), 'utf8')).replace('/src/styles.css', './styles.css').replace('/src/main.ts', './main.js').replaceAll('src="/logo.svg"', 'src="./logo.svg"')
  await fs.writeFile(path.join(temp, 'index.html'), html)
  await fs.copyFile(path.join(root, 'src/renderer/src/styles.css'), path.join(temp, 'styles.css'))
  await fs.copyFile(path.join(root, 'build/logo.svg'), path.join(temp, 'logo.svg'))
  ipcMain.handle('update:state:get', () => state)
  ipcMain.handle('update:action', (_event, action) => {
    actions.push(action)
    if (action === 'dismiss') { state = { ...state, visible: false, revision: state.revision + 1 }; win.webContents.send('update:state:changed', state) }
    return { ok: true, value: true }
  })
  win = new BrowserWindow({ width: 1000, height: 700, show: false, frame: false, webPreferences: { preload: path.join(temp, 'preload.cjs'), contextIsolation: true, sandbox: false, offscreen: true } })
  win.webContents.on('console-message', event => { if (event.level === 'error') errors.push(event.message) })
  await win.loadFile(path.join(temp, 'index.html')); await pause(200)
  await check(`!document.querySelector('#update-dialog').open`, 'No update modal before an update event')
  // Real preload IPC, with another modal already open underneath.
  await run(`document.querySelector('#settings-dialog').showModal()`)
  await send({ phase: 'available', version: '1.0.8' })
  await check(`document.querySelector('#update-dialog').open && document.activeElement.id==='update-primary' && document.querySelector('#update-primary').textContent.trim()==='Download'`, 'Available update opens above settings with a focused download action')
  await check(`document.querySelector('.update-brand img').complete && document.querySelector('.update-brand img').naturalWidth>0`, 'Update brand asset loads')
  await shot('01-available')
  await run(`document.querySelector('#update-later').click()`); await pause(80)
  assert.equal(actions.at(-1), 'dismiss')
  await check(`!document.querySelector('#update-dialog').open && document.querySelector('#settings-dialog').open`, 'Later dismisses only the update modal')
  await send({ phase: 'available', version: '1.0.8' })
  await run(`document.querySelector('#update-primary').click()`); await pause(80)
  assert.equal(actions.at(-1), 'download')
  await send({ phase: 'downloading', version: '1.0.8' })
  await check(`document.querySelector('#update-progress').matches(':indeterminate') && document.querySelector('#update-actions').hidden && document.querySelector('#update-close').hidden`, 'Download starts with activity feedback and no premature install action')
  await send({ phase: 'downloading', version: '1.0.8', progress: { percent: 63.8, transferred: 126000000, total: 200000000, bytesPerSecond: 8000000 } })
  await check(`document.querySelector('#update-progress').value===63.8 && document.querySelector('#update-percent').textContent==='63%' && document.querySelector('#update-size').textContent==='126.0 / 200.0 MB'`, 'Download shows measured percent and transfer size')
  await shot('02-downloading')
  const count = actions.length
  await run(`document.querySelector('#update-dialog').dispatchEvent(new Event('cancel',{cancelable:true}))`)
  await pause(80)
  assert.equal(actions.length, count)
  await check(`document.querySelector('#update-dialog').open`, 'Escape cannot hide an active download')
  await send({ phase: 'downloaded', version: '1.0.8' })
  await check(`document.querySelector('#update-primary').title==='Restart and install update' && document.querySelector('#update-download').hidden && !document.querySelector('#update-actions').hidden`, 'Ready update offers explicit restart and install')
  await shot('03-ready')
  // Old snapshots must not overwrite a newer event after an IPC/reload race.
  win.webContents.send('update:state:changed', { revision: 1, phase: 'available', visible: true, channel: 'stable' })
  await pause(80)
  await check(`document.querySelector('#update-title').textContent==='Update ready'`, 'Stale snapshots never regress the modal')
  await win.reload(); await pause(220)
  await check(`document.querySelector('#update-title').textContent==='Update ready' && document.querySelector('#update-dialog').open`, 'Reload restores a downloaded update through the real preload')
  await run(`document.querySelector('#update-primary').click()`); await pause(80)
  assert.equal(actions.at(-1), 'install')
  await send({ phase: 'installing', version: '1.0.8' })
  await check(`document.querySelector('#update-title').textContent==='Restarting…' && document.querySelector('#update-progress').matches(':indeterminate')`, 'Restart transition keeps activity visible before shutdown')
  await send({ phase: 'error', version: '1.0.8', retry: 'download', error: 'Check your connection and try again.' })
  await check(`!document.querySelector('#update-error').hidden && document.querySelector('#update-primary').textContent.trim()==='Retry'`, 'Errors use the custom modal with retry')
  await shot('04-error')
  await run(`document.querySelector('#update-primary').click()`); await pause(80)
  assert.equal(actions.at(-1), 'retry')
  win.setSize(360, 520); await pause(100)
  await send({ phase: 'downloaded', version: '1.0.8-beta.1' })
  await check(`(() => { const d=document.querySelector('#update-dialog'); const r=d.getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth && d.scrollWidth<=d.clientWidth && Array.from(d.querySelectorAll('button')).filter(b=>b.getClientRects().length).every(b=>b.getBoundingClientRect().right<=r.right) })()`, 'Compact modal and actions fit narrow windows')
  await shot('05-ready-small')
  assert.deepEqual(errors, [])
  console.log('All update UI checks passed. Screenshots: ' + output)
  win.destroy(); app.exit(0)
}).catch(error => { console.error(error); win?.destroy(); app.exit(1) })
