// Production participant/settings UI with deterministic voice transport.
const { app, BrowserWindow } = require('./silent-electron.cjs')
const { build } = require('./build-renderer.cjs')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname,'..')
const output = path.join(root,'release','voice-review')
const temp = require('node:fs').mkdtempSync(path.join(os.tmpdir(),'zodiak-voice-ui-'))
app.setPath('userData',path.join(temp,'profile'));app.setPath('sessionData',path.join(temp,'session'))
app.commandLine.appendSwitch('use-fake-device-for-media-stream')
app.commandLine.appendSwitch('use-fake-ui-for-media-stream')
app.commandLine.appendSwitch('autoplay-policy','no-user-gesture-required')
let win
const errors=[]
const run=code=>win.webContents.executeJavaScript(code,true)
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms))
const click=async selector=>{await run(`document.querySelector(${JSON.stringify(selector)}).click()`);await pause(80)}
const check=async(code,label)=>{for(let attempt=0;attempt<80;attempt++){if(await run(code)){console.log('PASS '+label);return}await pause(25)}throw Error(label)}
const timeout=setTimeout(()=>{console.error('Voice UI test timed out');app.exit(1)},45000)
app.whenReady().then(async()=>{
  await fs.mkdir(output,{recursive:true})
  await build({entryPoints:[path.join(root,'src/renderer/src/main.ts')],bundle:true,format:'esm',outfile:path.join(temp,'main.js'),plugins:[{name:'test-session',setup(build){build.onResolve({filter:/^\.\/session$/},()=>({path:path.join(root,'tests/ui-session.ts')}))}}]})
  const html=(await fs.readFile(path.join(root,'src/renderer/index.html'),'utf8')).replace('/src/styles.css','./styles.css').replace('/src/main.ts','./main.js').replaceAll('src="/logo.svg"','src="./logo.svg"')
  await fs.writeFile(path.join(temp,'index.html'),html)
  await fs.copyFile(path.join(root,'src/renderer/src/styles.css'),path.join(temp,'styles.css'))
  await fs.copyFile(path.join(root,'build/logo.svg'),path.join(temp,'logo.svg'))
  win=new BrowserWindow({width:1360,height:860,show:false,frame:false,webPreferences:{preload:path.join(root,'tests/ui-preload.cjs'),contextIsolation:true,sandbox:false,backgroundThrottling:false,offscreen:true}})
  win.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message)})
  await win.loadFile(path.join(temp,'index.html'));await pause(400)
  await run(`navigator.mediaDevices.enumerateDevices=async()=>[{kind:'audioinput',deviceId:'default',label:'Default'},{kind:'audioinput',deviceId:'usb-mic',label:'USB Microphone'},{kind:'audiooutput',deviceId:'default',label:'Default'}];void 0`)
  await click('#lobby-settings');await click('#settings-tab-audio');await click('#voice-loopback')
  await check(`!!document.querySelector('audio[data-voice-loopback]')&&!document.querySelector('audio[data-voice-loopback]').paused`, 'Microphone test also works before joining a room')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'})
  win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'})
  await check(`!document.querySelector('#settings-dialog').open&&!document.querySelector('audio[data-voice-loopback]')&&document.querySelector('#voice-loopback').getAttribute('aria-pressed')==='false'`, 'Escape closes settings and stops microphone test')
  await click('.room')
  await check(`document.querySelector('#voice-mute').getAttribute('aria-pressed')==='true'&&!document.querySelector('#voice-mute').disabled`, 'Room starts muted with voice controls available')
  await check(`document.querySelector('[data-participant-id="jo"] .member-voice-status').children.length===2`, 'Deafened participant has microphone and headphones status icons')
  await click('#voice-mute');await click('#voice-deafen')
  await check(`!document.querySelector('#voice-mute').disabled&&document.querySelector('#voice-mute').getAttribute('aria-pressed')==='true'&&document.querySelector('#voice-deafen').title==='Undeafen'&&getComputedStyle(document.querySelector('#voice-mute')).opacity==='0.45'&&getComputedStyle(document.querySelector('#voice-mute')).color==='rgb(238, 120, 133)'`, 'Deafen keeps the microphone clickable with the same dim red appearance')
  await click('#voice-deafen')
  await check(`document.querySelector('#voice-mute').getAttribute('aria-pressed')==='false'`, 'Undeafening restores the previously unmuted microphone')
  await click('#voice-mute');await click('#voice-deafen');await click('#voice-deafen')
  await check(`document.querySelector('#voice-mute').getAttribute('aria-pressed')==='true'`, 'Undeafening preserves a previous self-mute')
  await click('#voice-deafen');await click('#voice-mute')
  await check(`!window.uiTest.voice.muted&&!window.uiTest.voice.deafened&&document.querySelector('#voice-deafen').getAttribute('aria-pressed')==='false'&&getComputedStyle(document.querySelector('#voice-mute')).opacity==='1'`, 'Unmuting while deafened clears both states even when previously self-muted')
  await click('#voice-mute')
  await run(`window.uiTest.emitVoice({participants:window.uiTest.voice.participants.map(person=>person.id==='sam'?{...person,speaking:true}:person)})`)
  await pause(160)
  await check(`document.querySelector('[data-participant-id="sam"]').classList.contains('is-speaking')&&getComputedStyle(document.querySelector('[data-participant-id="sam"] .member-name')).color==='rgb(255, 255, 255)'`, 'Speaking gives the participant avatar a green border and a white name')
  await fs.writeFile(path.join(output,'01-speaking.png'),(await win.webContents.capturePage()).toPNG())
  await click('[data-participant-id="sam"] .member-voice-mute')
  await check(`document.querySelector('#participant-audio').matches(':popover-open')&&!window.uiTest.voice.participants.find(person=>person.id==='sam').locallyMuted&&document.querySelector('#participant-audio output').value==='100%'`, 'Participant microphone opens audio dropdown without muting')
  await check(`(()=>{const dropdown=document.querySelector('#participant-audio').getBoundingClientRect();const member=document.querySelector('[data-participant-id="sam"]').getBoundingClientRect();const slider=document.querySelector('#participant-audio-volume').getBoundingClientRect();return dropdown.top>=member.bottom&&dropdown.left>=member.left&&dropdown.width<=220&&slider.width>slider.height&&document.querySelector('#participant-audio').textContent==='100%'})()`, 'Dropdown opens below the participant with a horizontal slider and only a percentage as text')
  await run(`document.querySelector('#participant-audio-volume').value='35';document.querySelector('#participant-audio-volume').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.voice.participants.find(person=>person.id==='sam').volume===.35&&document.querySelector('#participant-audio output').value==='35%'&&window.uiTest.voice.participants.find(person=>person.id==='jo').volume===1&&window.uiTest.streamVolume===1`, 'Individual volume updates immediately without affecting another participant or screen audio')
  await pause(160)
  await fs.writeFile(path.join(output,'03-participant-volume.png'),(await win.webContents.capturePage()).toPNG())
  await click('#participant-audio button')
  await check(`document.querySelector('[data-participant-id="sam"] .member-voice-status .voice-local-muted')&&!document.querySelector('[data-participant-id="sam"]').classList.contains('is-speaking')`, 'Manual mute shows a red microphone and stops the speaking highlight')
  await check(`document.querySelector('[data-participant-id="sam"] .member-voice-mute').hidden`, 'Locally muted participant has one visible red microphone control')
  await check(`document.querySelector('#participant-audio').matches(':popover-open')&&document.querySelector('#participant-audio button').getAttribute('aria-pressed')==='true'&&document.querySelector('#participant-audio output').value==='35%'`, 'Muting keeps the dropdown open and preserves the chosen volume')
  await run(`document.querySelector('#participant-audio-volume').value='20';document.querySelector('#participant-audio-volume').dispatchEvent(new Event('input'))`)
  await check(`!window.uiTest.voice.participants.find(person=>person.id==='sam').locallyMuted&&document.querySelector('#participant-audio output').value==='20%'`, 'Moving the slider unmutes the participant like screen audio controls')
  await click('[data-participant-id="jo"] .member-voice-status button')
  await check(`document.querySelectorAll('.participant-audio:popover-open').length===1&&document.querySelector('#participant-audio').getAttribute('aria-label')==='Audio for Jordan Lee'&&document.querySelector('#participant-audio output').value==='100%'`, 'Muted microphone status opens the dropdown for that participant and replaces the previous dropdown')
  await click('#room-title')
  await check(`!document.querySelector('#participant-audio').matches(':popover-open')`, 'Clicking outside closes the audio dropdown')
  await click('[data-participant-id="sam"] .member-voice-mute')
  await check(`document.querySelector('#participant-audio output').value==='20%'`, 'Reopening restores this participant volume')
  await run(`document.querySelector('#participant-audio-volume').value='0';document.querySelector('#participant-audio-volume').dispatchEvent(new Event('input'));window.uiTest.emitChat({})`)
  await check(`document.querySelector('#participant-audio').matches(':popover-open')&&document.querySelector('#participant-audio output').value==='0%'&&document.querySelector('[data-participant-id="sam"] .member-voice-mute').getAttribute('aria-expanded')==='true'`, 'Zero volume and an updated participant list preserve the open dropdown')
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'})
  win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'})
  await check(`!document.querySelector('#participant-audio').matches(':popover-open')&&document.activeElement.matches('[data-participant-id="sam"] .member-voice-mute')`, 'Escape closes dropdown and restores focus to participant microphone')
  await click('[data-participant-id="sam"] .member-voice-mute');await click('#participant-audio button');await click('#room-title')
  await check(`(()=>{const profile=document.querySelector('.profile-bar').getBoundingClientRect();const controls=document.querySelector('#call-controls').getBoundingClientRect();return Math.abs(profile.top-controls.top)<1&&Math.abs(profile.bottom-controls.bottom)<1})()`, 'Profile and room control footers align vertically')
  await click('[data-settings]')
  await check(`document.querySelector('#settings-tab-account').getAttribute('aria-selected')==='true'&&!document.querySelector('#settings-panel-account').hidden&&document.querySelector('#settings-panel-audio').hidden&&document.querySelector('#settings-tab-account svg')`, 'Settings starts in Account with the person icon and name field')
  await run(`document.querySelector('#settings-tab-account').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}))`)
  await check(`document.activeElement.id==='settings-tab-audio'&&!document.querySelector('#settings-panel-audio').hidden&&document.querySelector('#settings-panel-account').hidden`, 'Settings tabs support keyboard navigation and separate content')
  await check(`document.querySelector('#settings-tab-audio svg')&&document.querySelector('#settings-tab-system svg')&&!document.querySelector('[id^=chat-position]')&&document.querySelector('#voice-enabled').closest('[role=tabpanel]').id==='settings-panel-audio'`, 'Audio and System have icons; voice sits in Audio and chat placement is removed')
  await check(`document.querySelector('#voice-noise-suppression').labels[0].textContent==='Noise supression'&&document.querySelector('#voice-enabled').closest('label').nextElementSibling.contains(document.querySelector('#voice-noise-suppression'))&&document.querySelector('#voice-noise-suppression').checked`, 'Noise supression is initially on and appears directly below Voice chat')
  await check(`document.querySelector('#voice-loopback').nextElementSibling.id==='refresh-voice-input'&&document.querySelector('#voice-loopback').previousElementSibling.contains(document.querySelector('#voice-input'))&&document.querySelector('#voice-loopback svg')`, 'Microphone test button sits between the input selector and refresh')
  await check(`document.querySelector('#voice-noise-gate').checked&&document.querySelector('#voice-auto-sensitivity').checked&&document.querySelector('#voice-input-sensitivity').disabled&&document.querySelector('#voice-echo-cancellation').checked&&!document.querySelector('#voice-auto-gain-control').checked`, 'Automatic gain control defaults off; gate and echo cancellation default on')
  await click('#voice-auto-sensitivity');await click('#voice-echo-cancellation');await click('#voice-auto-gain-control')
  await run(`document.querySelector('#voice-input-sensitivity').value='-42';document.querySelector('#voice-input-sensitivity').dispatchEvent(new Event('input'))`)
  await check(`!document.querySelector('#voice-input-sensitivity').disabled&&document.querySelector('#voice-input-sensitivity-value').value==='-42 dB'&&window.uiTest.processing.inputSensitivity===-42&&!window.uiTest.processing.echoCancellation&&window.uiTest.processing.autoGainControl`, 'Sensitivity and capture toggles preview immediately')
  await click('[data-close="settings-dialog"]');await click('[data-settings]');await click('#settings-tab-audio')
  await check(`document.querySelector('#voice-auto-sensitivity').checked&&document.querySelector('#voice-echo-cancellation').checked&&!document.querySelector('#voice-auto-gain-control').checked&&window.uiTest.processing.autoInputSensitivity&&window.uiTest.processing.echoCancellation&&!window.uiTest.processing.autoGainControl`, 'Cancel restores saved sensitivity and capture toggles')
  await check(`document.querySelector('#voice-suppression-strength').value==='80'&&document.querySelector('#voice-suppression-strength-value').textContent==='80%'&&!document.querySelector('#voice-suppression-strength').disabled`, 'Suppression strength starts at the 80% default')
  await click('[data-close="settings-dialog"]');await click('#voice-mute');await click('[data-settings]');await click('#settings-tab-audio')
  await click('#voice-loopback')
  await check(`document.querySelector('#voice-loopback').getAttribute('aria-pressed')==='true'&&document.querySelector('audio[data-voice-loopback]')&&!document.querySelector('audio[data-voice-loopback]').paused&&window.uiTest.voice.muted&&window.uiTest.voice.deafened&&window.uiTest.volume===0`, 'Microphone test plays locally while room microphone and all incoming audio are muted')
  await check(`document.querySelector('[data-participant-id="me"] .member-voice-status').children.length===2&&['voice-mute','voice-deafen','voice-focus-mute','voice-focus-deafen'].every(id=>document.getElementById(id).getAttribute('aria-pressed')==='true'&&document.getElementById(id).disabled)`, 'Participant status and bottom/focus controls show microphone muted and deafened during testing')
  await run(`document.querySelector('#audio-volume').value='80';document.querySelector('#audio-volume').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.volume===0`, 'Output slider cannot restore incoming app audio while testing')
  await run(`document.querySelector('#voice-suppression-strength').value='45';document.querySelector('#voice-suppression-strength').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.suppressionStrength===.45&&document.querySelector('#voice-suppression-strength-value').textContent==='45%'`, 'Suppression strength previews immediately')
  await click('#voice-loopback')
  await check(`document.querySelector('#voice-loopback').getAttribute('aria-pressed')==='false'&&!document.querySelector('audio[data-voice-loopback]')`, 'Microphone test button toggles playback off')
  await check(`!window.uiTest.voice.muted&&!window.uiTest.voice.deafened&&window.uiTest.volume===.8&&document.querySelector('#voice-mute').getAttribute('aria-pressed')==='false'&&document.querySelector('[data-participant-id="me"] .member-voice-status').children.length===0`, 'Stopping testing restores previously unmuted voice, participant icons, and the chosen incoming volume')
  await click('#voice-loopback')
  await check(`!!document.querySelector('audio[data-voice-loopback]')`, 'Microphone test can be restarted')
  await click('#voice-noise-suppression')
  await check(`window.uiTest.noiseSuppression===false`, 'Noise suppression changes immediately in the current room')
  await run(`document.querySelector('#voice-input-volume').value='40';document.querySelector('#voice-input-volume').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.inputVolume===.4&&document.querySelector('#voice-input-volume-value').textContent==='40%'`, 'Input slider changes microphone gain immediately')
  await click('[data-close="settings-dialog"]')
  await check(`window.uiTest.inputVolume===1&&document.querySelector('#voice-input-volume').value==='100'`, 'Cancel restores the saved microphone volume')
  await check(`window.uiTest.noiseSuppression&&document.querySelector('#voice-noise-suppression').checked`, 'Cancel restores the saved noise suppression setting')
  await check(`document.querySelector('#voice-suppression-strength').value==='80'&&window.uiTest.suppressionStrength===.8`, 'Cancel restores the saved suppression strength')
  await check(`document.querySelector('#voice-loopback').getAttribute('aria-pressed')==='false'&&!document.querySelector('audio[data-voice-loopback]')`, 'Closing settings automatically stops microphone test')
  await click('[data-settings]');await click('#settings-tab-audio')
  await click('#voice-auto-sensitivity');await click('#voice-auto-gain-control')
  await run(`document.querySelector('#voice-input-sensitivity').value='-48';document.querySelector('#voice-input-sensitivity').dispatchEvent(new Event('input'))`)
  await run(`document.querySelector('#voice-suppression-strength').value='55';document.querySelector('#voice-suppression-strength').dispatchEvent(new Event('input'))`)
  await click('#voice-loopback')
  await check(`!!document.querySelector('audio[data-voice-loopback]')`, 'Reopened settings can test the microphone')
  await click('#voice-enabled')
  await check(`document.querySelector('#voice-loopback').disabled&&document.querySelector('#voice-loopback').getAttribute('aria-pressed')==='false'&&!document.querySelector('audio[data-voice-loopback]')`, 'Disabling voice stops microphone test and disables its button')
  await click('#voice-enabled')
  await click('#voice-loopback')
  await check(`!!document.querySelector('audio[data-voice-loopback]')`, 'Enabling voice allows a new microphone test')
  await click('#settings-tab-account')
  await check(`!document.querySelector('audio[data-voice-loopback]')`, 'Leaving Audio settings stops microphone test')
  await click('#settings-tab-audio')
  await run(`document.querySelector('#voice-input-volume').value='65';document.querySelector('#voice-input-volume').dispatchEvent(new Event('input'))`)
  await click('#voice-loopback')
  await check(`!!document.querySelector('audio[data-voice-loopback]')`, 'Microphone test can run before saving settings')
  await click('#save-settings')
  await check(`!document.querySelector('#settings-dialog').open&&!document.querySelector('audio[data-voice-loopback]')&&document.querySelector('#voice-loopback').getAttribute('aria-pressed')==='false'`, 'Saving settings also stops microphone test')
  await click('[data-settings]');await click('#settings-tab-audio')
  await check(`document.querySelector('#voice-input option[value="usb-mic"]').textContent==='USB Microphone'`, 'Settings list Windows microphone devices')
  await run(`document.querySelector('#voice-input').value='usb-mic'`);await click('#save-settings')
  await check(`window.uiTest.voiceDevice==='usb-mic'&&window.uiTest.inputVolume===.65&&document.querySelector('#voice-input-volume').value==='65'`, 'Saving applies input device and volume to the current room')
  await check(`window.uiTest.noiseSuppression&&document.querySelector('#voice-noise-suppression').checked`, 'Saving preserves noise suppression when the modal is reopened')
  await check(`!document.querySelector('#voice-auto-sensitivity').checked&&document.querySelector('#voice-auto-gain-control').checked&&document.querySelector('#voice-input-sensitivity').value==='-48'&&window.uiTest.processing.inputSensitivity===-48`, 'Saving remembers manual sensitivity and gain control')
  await check(`document.querySelector('#voice-suppression-strength').value==='55'&&window.uiTest.suppressionStrength===.55`, 'Saving remembers the chosen suppression strength')
  await click('[data-settings]');await click('#settings-tab-audio');await click('#voice-enabled')
  await check(`document.querySelector('#voice-input').disabled&&document.querySelector('#voice-input-volume').disabled`, 'Disabling voice also disables microphone selection')
  await check(`document.querySelector('#voice-noise-suppression').disabled&&getComputedStyle(document.querySelector('#voice-noise-suppression').closest('label')).opacity==='0.45'&&!window.uiTest.voice.enabled`, 'Voice disable immediately stops voice and greys out noise suppression')
  await check(`document.querySelector('#voice-noise-suppression').checked`, 'Noise suppression preference survives while voice is disabled')
  await click('#save-settings')
  await check(`document.querySelector('#voice-mute').disabled&&document.querySelector('#voice-deafen').disabled`, 'Saved voice disable makes room controls unavailable')
  await click('[data-settings]');await click('#settings-tab-audio');await click('#voice-enabled');await click('[data-close="settings-dialog"]')
  await check(`!document.querySelector('#voice-enabled').checked`, 'Closing settings discards unsaved voice changes')
  await click('[data-settings]');await click('#settings-tab-audio');await click('#voice-enabled');await click('#save-settings')
  await click('[data-participant-id="sam"] .member-voice-status button')
  await click('#participant-audio button');await click('#room-title')
  await run(`document.body.classList.add('theater')`)
  await check(`getComputedStyle(document.querySelector('#voice-focus-mute')).display!=='none'&&getComputedStyle(document.querySelector('#voice-focus-deafen')).display!=='none'`, 'Focus view keeps microphone and deafen controls accessible')
  await click('#voice-focus-deafen')
  await check(`document.querySelector('#voice-deafen').getAttribute('aria-pressed')==='true'&&!document.querySelector('#voice-focus-mute').disabled&&getComputedStyle(document.querySelector('#voice-focus-mute')).opacity==='0.45'`, 'Focus-view deafen updates both sets of controls and keeps the microphone clickable')
  await click('#voice-focus-mute')
  await check(`!window.uiTest.voice.muted&&!window.uiTest.voice.deafened&&document.querySelector('#voice-mute').getAttribute('aria-pressed')==='false'&&document.querySelector('#voice-focus-deafen').getAttribute('aria-pressed')==='false'`, 'Focus-view unmute also undeafens and updates both sets of controls')
  await run(`document.body.classList.remove('theater')`)
  await win.setSize(900,620);await pause(120)
  await check(`document.documentElement.scrollWidth<=innerWidth&&Array.from(document.querySelectorAll('.profile-bar button')).every(button=>{const r=button.getBoundingClientRect();return r.width>0&&r.x>=0&&r.right<=innerWidth})`, 'Voice controls fit the compact window')
  await check(`(()=>{const a=document.querySelector('.profile-bar').getBoundingClientRect();const b=document.querySelector('#call-controls').getBoundingClientRect();return Math.abs(a.top-b.top)<1})()`, 'Footers stay aligned in a compact window')
  await click('[data-settings]');await click('#settings-tab-audio');await pause(160)
  await fs.writeFile(path.join(output,'02-settings-compact.png'),(await win.webContents.capturePage()).toPNG())
  await run(`document.querySelector('#voice-auto-gain-control').scrollIntoView({block:'end'})`)
  await check(`(()=>{const panel=document.querySelector('.settings-panels').getBoundingClientRect();const agc=document.querySelector('#voice-auto-gain-control').getBoundingClientRect();const save=document.querySelector('#save-settings').getBoundingClientRect();return agc.top>=panel.top&&agc.bottom<=panel.bottom&&save.bottom<=innerHeight})()`, 'Compact Audio settings scroll to every processing control while keeping Save visible')
  await fs.writeFile(path.join(output,'05-voice-processing.png'),(await win.webContents.capturePage()).toPNG())
  await run(`document.querySelector('.settings-panels').scrollTop=0`)
  await check(`(()=>{const d=document.querySelector('#settings-dialog').getBoundingClientRect();const save=document.querySelector('#save-settings').getBoundingClientRect();const panel=document.querySelector('.settings-panels').getBoundingClientRect();const strength=document.querySelector('#voice-suppression-strength').getBoundingClientRect();return d.width<=680&&d.height<=innerHeight&&save.bottom<=d.bottom&&strength.bottom<=panel.bottom-8})()`, 'Compact Audio settings show the full suppression slider above the footer without clipping')
  await fs.writeFile(path.join(output,'02-settings-compact.png'),(await win.webContents.capturePage()).toPNG())
  await click('#settings-tab-interface');await check(`!document.querySelector('#settings-panel-interface').hidden&&document.querySelector('#show-stream-statistics').closest('[role=tabpanel]').id==='settings-panel-interface'`, 'Interface contains statistics and chat bubbles')
  await click('#settings-tab-system');await check(`!document.querySelector('#settings-panel-system').hidden&&document.querySelector('#check-for-updates').closest('[role=tabpanel]').id==='settings-panel-system'`, 'System contains update controls')
  await click('[data-close="settings-dialog"]')
  await click('[data-participant-id="sam"] .member-voice-mute')
  await check(`document.querySelector('#participant-audio').getBoundingClientRect().right<=innerWidth`, 'Participant dropdown fits the compact window')
  await run(`window.uiTest.emitParticipants([{id:'me',name:'Alex Morgan',local:true},{id:'jo',name:'Jordan Lee',local:false}])`)
  await check(`!document.querySelector('#participant-audio').matches(':popover-open')`, 'Participant departure closes their dropdown')
  await click('[data-participant-id="jo"] .member-voice-status button');await click('#leave')
  await check(`!document.querySelector('#participant-audio').matches(':popover-open')`, 'Leaving the room closes participant audio controls')
  await check(`document.querySelector('#room-sidebar').hidden&&document.querySelector('#call-controls').hidden`, 'Leaving hides room voice controls')
  await click('.room[title="watch-party"]')
  await click('[data-participant-id="sam"] .member-voice-mute')
  await check(`document.querySelector('#participant-audio-volume').value==='0'&&window.uiTest.voice.participants.find(person=>person.id==='sam').volume===0`, 'Joining another room restores the saved zero volume')
  await run(`document.querySelector('#participant-audio-volume').value='42';document.querySelector('#participant-audio-volume').dispatchEvent(new Event('input'));window.uiTest.emitParticipants([{id:'me',name:'Alex Morgan',local:true},{id:'sam',name:'Same Name',local:false},{id:'jo',name:'Same Name',local:false}])`)
  await check(`window.sharescreen.getParticipantPreferences('ws://localhost:7880').then(result=>result.value.sam.name==='Same Name'&&result.value.sam.volume===.42&&result.value.jo.name==='Same Name'&&result.value.jo.volume===1)`, 'Duplicate names stay separate by identity; renaming keeps the selected volume')
  await click('#leave');await click('.room')
  await check(`window.uiTest.voice.participants.find(person=>person.id==='sam').volume===.42&&window.uiTest.voice.participants.find(person=>person.id==='jo').volume===1`, 'Volume persists across repeated room visits without changing another participant')
  await click('#leave')
  if(errors.length)throw Error(errors.join('\n'))
  console.log('All voice UI checks passed. Screenshots: '+output)
  clearTimeout(timeout);win.destroy();app.exit(0)
}).catch(error=>{console.error(error);clearTimeout(timeout);win?.destroy();app.exit(1)})
