// Production participant/settings UI with deterministic voice transport.
const { app, BrowserWindow } = require('electron')
const { build } = require('esbuild')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const root = path.resolve(__dirname,'..')
const output = path.join(root,'release','voice-review')
const temp = require('node:fs').mkdtempSync(path.join(os.tmpdir(),'zodiak-voice-ui-'))
app.setPath('userData',path.join(temp,'profile'));app.setPath('sessionData',path.join(temp,'session'))
let win
const errors=[]
const run=code=>win.webContents.executeJavaScript(code,true)
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms))
const click=async selector=>{await run(`document.querySelector(${JSON.stringify(selector)}).click()`);await pause(80)}
const check=async(code,label)=>{for(let attempt=0;attempt<20;attempt++){if(await run(code)){console.log('PASS '+label);return}await pause(25)}throw Error(label)}
const timeout=setTimeout(()=>{console.error('Voice UI test timed out');app.exit(1)},45000)
app.whenReady().then(async()=>{
  await fs.mkdir(output,{recursive:true})
  await build({entryPoints:[path.join(root,'src/renderer/src/main.ts')],bundle:true,format:'esm',outfile:path.join(temp,'main.js'),plugins:[{name:'test-session',setup(build){build.onResolve({filter:/^\.\/session$/},()=>({path:path.join(root,'tests/ui-session.ts')}))}}]})
  const html=(await fs.readFile(path.join(root,'src/renderer/index.html'),'utf8')).replace('/src/styles.css','./styles.css').replace('/src/main.ts','./main.js').replace('src="/logo.svg"','src="./logo.svg"')
  await fs.writeFile(path.join(temp,'index.html'),html)
  await fs.copyFile(path.join(root,'src/renderer/src/styles.css'),path.join(temp,'styles.css'))
  await fs.copyFile(path.join(root,'build/logo.svg'),path.join(temp,'logo.svg'))
  win=new BrowserWindow({width:1360,height:860,show:false,frame:false,webPreferences:{preload:path.join(root,'tests/ui-preload.cjs'),contextIsolation:true,sandbox:false,backgroundThrottling:false,offscreen:true}})
  win.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message)})
  await win.loadFile(path.join(temp,'index.html'));await pause(400)
  await run(`navigator.mediaDevices.enumerateDevices=async()=>[{kind:'audioinput',deviceId:'default',label:'Default'},{kind:'audioinput',deviceId:'usb-mic',label:'USB Microphone'},{kind:'audiooutput',deviceId:'default',label:'Default'}];void 0`)
  await click('.room')
  await check(`document.querySelector('#voice-mute').getAttribute('aria-pressed')==='true'&&!document.querySelector('#voice-mute').disabled`, 'Room starts muted with voice controls available')
  await check(`document.querySelector('[data-participant-id="jo"] .member-voice-status').children.length===2`, 'Deafened participant has microphone and headphones status icons')
  await click('#voice-mute');await click('#voice-deafen')
  await check(`document.querySelector('#voice-mute').disabled&&document.querySelector('#voice-mute').getAttribute('aria-pressed')==='true'&&document.querySelector('#voice-deafen').title==='Undeafen'`, 'Deafen automatically mutes and prevents unmuting until undeafened')
  await click('#voice-deafen')
  await check(`document.querySelector('#voice-mute').getAttribute('aria-pressed')==='false'`, 'Undeafening restores the previously unmuted microphone')
  await click('#voice-mute');await click('#voice-deafen');await click('#voice-deafen')
  await check(`document.querySelector('#voice-mute').getAttribute('aria-pressed')==='true'`, 'Undeafening preserves a previous self-mute')
  await run(`window.uiTest.emitVoice({participants:window.uiTest.voice.participants.map(person=>person.id==='sam'?{...person,speaking:true}:person)})`)
  await pause(160)
  await check(`document.querySelector('[data-participant-id="sam"]').classList.contains('is-speaking')&&getComputedStyle(document.querySelector('[data-participant-id="sam"] .member-name')).color==='rgb(255, 255, 255)'`, 'Speaking gives the participant avatar a green border and a white name')
  await fs.writeFile(path.join(output,'01-speaking.png'),(await win.webContents.capturePage()).toPNG())
  await click('[data-participant-id="sam"] .member-voice-mute')
  await check(`document.querySelector('[data-participant-id="sam"] .member-voice-status .voice-local-muted')&&!document.querySelector('[data-participant-id="sam"]').classList.contains('is-speaking')`, 'Manual mute shows a red microphone and stops the speaking highlight')
  await check(`document.querySelector('[data-participant-id="sam"] .member-voice-mute').hidden`, 'Locally muted participant has one visible red microphone control')
  await check(`(()=>{const profile=document.querySelector('.profile-bar').getBoundingClientRect();const controls=document.querySelector('#call-controls').getBoundingClientRect();return Math.abs(profile.top-controls.top)<1&&Math.abs(profile.bottom-controls.bottom)<1})()`, 'Profile and room control footers align vertically')
  await click('[data-settings]')
  await check(`document.querySelector('#settings-tab-account').getAttribute('aria-selected')==='true'&&!document.querySelector('#settings-panel-account').hidden&&document.querySelector('#settings-panel-audio').hidden&&document.querySelector('#settings-tab-account svg')`, 'Settings starts in Account with the person icon and name field')
  await run(`document.querySelector('#settings-tab-account').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}))`)
  await check(`document.activeElement.id==='settings-tab-audio'&&!document.querySelector('#settings-panel-audio').hidden&&document.querySelector('#settings-panel-account').hidden`, 'Settings tabs support keyboard navigation and separate content')
  await check(`document.querySelector('#settings-tab-audio svg')&&document.querySelector('#settings-tab-system svg')&&!document.querySelector('[id^=chat-position]')&&document.querySelector('#voice-enabled').closest('[role=tabpanel]').id==='settings-panel-audio'`, 'Audio and System have icons; voice sits in Audio and chat placement is removed')
  await run(`document.querySelector('#voice-input-volume').value='40';document.querySelector('#voice-input-volume').dispatchEvent(new Event('input'))`)
  await check(`window.uiTest.inputVolume===.4&&document.querySelector('#voice-input-volume-value').textContent==='40%'`, 'Input slider changes microphone gain immediately')
  await click('[data-close="settings-dialog"]')
  await check(`window.uiTest.inputVolume===1&&document.querySelector('#voice-input-volume').value==='100'`, 'Cancel restores the saved microphone volume')
  await click('[data-settings]');await click('#settings-tab-audio')
  await run(`document.querySelector('#voice-input-volume').value='65';document.querySelector('#voice-input-volume').dispatchEvent(new Event('input'))`)
  await check(`document.querySelector('#voice-input option[value="usb-mic"]').textContent==='USB Microphone'`, 'Settings list Windows microphone devices')
  await run(`document.querySelector('#voice-input').value='usb-mic'`);await click('#save-settings')
  await check(`window.uiTest.voiceDevice==='usb-mic'&&window.uiTest.inputVolume===.65&&document.querySelector('#voice-input-volume').value==='65'`, 'Saving applies input device and volume to the current room')
  await click('[data-settings]');await click('#settings-tab-audio');await click('#voice-enabled')
  await check(`document.querySelector('#voice-input').disabled&&document.querySelector('#voice-input-volume').disabled`, 'Disabling voice also disables microphone selection')
  await click('#save-settings')
  await check(`document.querySelector('#voice-mute').disabled&&document.querySelector('#voice-deafen').disabled`, 'Saved voice disable makes room controls unavailable')
  await click('[data-settings]');await click('#settings-tab-audio');await click('#voice-enabled');await click('[data-close="settings-dialog"]')
  await check(`!document.querySelector('#voice-enabled').checked`, 'Closing settings discards unsaved voice changes')
  await click('[data-settings]');await click('#settings-tab-audio');await click('#voice-enabled');await click('#save-settings')
  await click('[data-participant-id="sam"] .member-voice-status button')
  await run(`document.body.classList.add('theater')`)
  await check(`getComputedStyle(document.querySelector('#voice-focus-mute')).display!=='none'&&getComputedStyle(document.querySelector('#voice-focus-deafen')).display!=='none'`, 'Focus view keeps microphone and deafen controls accessible')
  await click('#voice-focus-deafen')
  await check(`document.querySelector('#voice-deafen').getAttribute('aria-pressed')==='true'&&document.querySelector('#voice-focus-mute').disabled`, 'Focus-view deafen updates both sets of controls')
  await click('#voice-focus-deafen')
  await run(`document.body.classList.remove('theater')`)
  await win.setSize(900,620);await pause(120)
  await check(`document.documentElement.scrollWidth<=innerWidth&&Array.from(document.querySelectorAll('.profile-bar button')).every(button=>{const r=button.getBoundingClientRect();return r.width>0&&r.x>=0&&r.right<=innerWidth})`, 'Voice controls fit the compact window')
  await check(`(()=>{const a=document.querySelector('.profile-bar').getBoundingClientRect();const b=document.querySelector('#call-controls').getBoundingClientRect();return Math.abs(a.top-b.top)<1})()`, 'Footers stay aligned in a compact window')
  await click('[data-settings]');await click('#settings-tab-audio');await pause(160)
  await fs.writeFile(path.join(output,'02-settings-compact.png'),(await win.webContents.capturePage()).toPNG())
  await check(`(()=>{const d=document.querySelector('#settings-dialog').getBoundingClientRect();const save=document.querySelector('#save-settings').getBoundingClientRect();const voice=document.querySelector('#voice-enabled').getBoundingClientRect();return d.width<=680&&d.height<=innerHeight&&save.bottom<=d.bottom&&voice.bottom<=save.top})()`, 'Compact Audio settings fit the window with the voice switch and Save visible')
  await fs.writeFile(path.join(output,'02-settings-compact.png'),(await win.webContents.capturePage()).toPNG())
  await click('#settings-tab-interface');await check(`!document.querySelector('#settings-panel-interface').hidden&&document.querySelector('#show-stream-statistics').closest('[role=tabpanel]').id==='settings-panel-interface'`, 'Interface contains statistics and chat bubbles')
  await click('#settings-tab-system');await check(`!document.querySelector('#settings-panel-system').hidden&&document.querySelector('#check-for-updates').closest('[role=tabpanel]').id==='settings-panel-system'`, 'System contains update controls')
  await click('[data-close="settings-dialog"]');await click('#leave')
  await check(`document.querySelector('#room-sidebar').hidden&&document.querySelector('#call-controls').hidden`, 'Leaving hides room voice controls')
  if(errors.length)throw Error(errors.join('\n'))
  console.log('All voice UI checks passed. Screenshots: '+output)
  clearTimeout(timeout);win.destroy();app.exit(0)
}).catch(error=>{console.error(error);clearTimeout(timeout);win?.destroy();app.exit(1)})
